LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.plan.CPlan Class Reference
org.lightjason.agentspeak.language.instantiable.plan.CPlan Class Reference
plan structure
Public Member Functions
CPlan (final ITrigger p_event, final List< IExecution > p_body, final Set< IAnnotation<?>> p_annotation)
ctor
CPlan (final ITrigger p_event, final IExpression p_condition, final List< IExecution > p_body, final Set< IAnnotation<?>> p_annotation)
ctor
final IFuzzyValue< Boolean > condition (final IContext p_context)
execute the plan condition
final IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
defines a plan-body operation
final Collection< IAnnotation<?> > getAnnotations ()
return unmodifieable annotation set
final List< IExecution > getBodyActions ()
returns unmodifieable list with plan actions
final ITrigger getTrigger ()
returns the trigger event
final double score (final IAgent<?> p_agent)
returns the scoring value of the execution structure
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
final boolean equals (final Object p_object)
IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
defines a plan-body operation
final int hashCode ()
final IContext instantiate (final IAgent<?> p_agent, final Stream< IVariable<?>> p_variable)
creates an individual execution context
double score (final IAgent<?> p_agent)
returns the scoring value of the execution structure
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Attributes
final IExpression m_condition
execution condition / expression
final ITrigger m_triggerevent
trigger event
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
IBaseInstantiable (final List< IExecution > p_action, final Set< IAnnotation<?>> p_annotation, final int p_hash)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
final List< IExecution > m_action
action list
final Map< IAnnotation.EType,
IAnnotation<?> > m_annotation
map with annotation (enum value for getting annotation object)
Detailed Description
Definition at line 53 of file language/instantiable/plan/CPlan.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.language.instantiable.plan.CPlan.CPlan (final ITrigger p_event, final List< IExecution > p_body, final Set< IAnnotation<?>> p_annotation)
Parameters
p_event trigger event
p_body plan body
p_annotation annotations
Definition at line 72 of file language/instantiable/plan/CPlan.java.
org.lightjason.agentspeak.language.instantiable.plan.CPlan.CPlan (final ITrigger p_event, final IExpression p_condition, final List< IExecution > p_body, final Set< IAnnotation<?>> p_annotation)
Parameters
p_event trigger event
p_condition execution condition
p_body plan body
p_annotation annotations
Definition at line 85 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_condition, and org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_triggerevent.
Member Function Documentation
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.instantiable.plan.CPlan.condition (final IContext p_context)
Parameters
p_context execution context
Returns
execution result
Implements org.lightjason.agentspeak.language.instantiable.plan.IPlan.
Definition at line 135 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_condition.
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.instantiable.plan.CPlan.execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
Parameters
p_context current execution context
p_parallel parallel execution
p_argument parameter of the action
p_return return values
p_annotation annotation
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 121 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from(), org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.getLiteral(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_triggerevent.
final Collection<IAnnotation<?> > org.lightjason.agentspeak.language.instantiable.plan.CPlan.getAnnotations ()
Returns
set with annotation
Implements org.lightjason.agentspeak.language.instantiable.plan.IPlan.
Definition at line 109 of file language/instantiable/plan/CPlan.java.
final List<IExecution> org.lightjason.agentspeak.language.instantiable.plan.CPlan.getBodyActions ()
Returns
action list;
Implements org.lightjason.agentspeak.language.instantiable.plan.IPlan.
Definition at line 115 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action.
final ITrigger org.lightjason.agentspeak.language.instantiable.plan.CPlan.getTrigger ()
Returns
trigger event
Implements org.lightjason.agentspeak.language.instantiable.plan.IPlan.
Definition at line 103 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_triggerevent.
final double org.lightjason.agentspeak.language.instantiable.plan.CPlan.score (final IAgent<?> p_agent)
Parameters
p_agent agent for which calculates the score value
Returns
score value
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 164 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_annotation.
final String org.lightjason.agentspeak.language.instantiable.plan.CPlan.toString ()
Definition at line 150 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action, org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_annotation, org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_condition, and org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_triggerevent.
final Stream<IVariable<?> > org.lightjason.agentspeak.language.instantiable.plan.CPlan.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 180 of file language/instantiable/plan/CPlan.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.getLiteral(), org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_condition, org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_triggerevent, org.lightjason.agentspeak.language.CCommon.recursiveliteral(), and org.lightjason.agentspeak.language.CCommon.recursiveterm().
Member Data Documentation
final IExpression org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_condition private
Definition at line 62 of file language/instantiable/plan/CPlan.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.CPlan.condition(), org.lightjason.agentspeak.language.instantiable.plan.CPlan.CPlan(), org.lightjason.agentspeak.language.instantiable.plan.CPlan.toString(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.variables().
final ITrigger org.lightjason.agentspeak.language.instantiable.plan.CPlan.m_triggerevent private
Definition at line 58 of file language/instantiable/plan/CPlan.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.CPlan.CPlan(), org.lightjason.agentspeak.language.instantiable.plan.CPlan.execute(), org.lightjason.agentspeak.language.instantiable.plan.CPlan.getTrigger(), org.lightjason.agentspeak.language.instantiable.plan.CPlan.toString(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.variables().