LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> > Class Reference
org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> > Class Reference
view of a beliefbase
Inherits IView< T >.
Public Member Functions
CView (final String p_name, final IBeliefbase< T > p_beliefbase)
ctor
CView (final String p_name, final IBeliefbase< T > p_beliefbase, final IView< T > p_parent)
ctor
final IView< T > add (final Stream< ILiteral > p_literal)
final IView< T > add (final ILiteral...p_literal)
final IView< T > add (final IPath p_path, final IView< T >...p_view)
final IView< T > add (final IView< T >...p_view)
final IBeliefbase< T > beliefbase ()
final IView< T > clear (final IPath...p_path)
final boolean containsLiteral (final IPath p_path)
final boolean containsView (final IPath p_path)
final boolean empty ()
final boolean equals (final Object p_object)
final IView< T > generate (final IViewGenerator< T > p_generator, final IPath...p_paths)
final int hashCode ()
final boolean hasParent ()
final String name ()
final IView< T > parent ()
final IPath path ()
final IView< T > remove (final IView< T > p_view)
final IView< T > remove (final Stream< ILiteral > p_literal)
final IView< T > remove (final ILiteral...p_literal)
final Stream< IView< T > > root ()
final int size ()
final Stream< ILiteral > stream (final IPath...p_path)
final Stream< ILiteral > stream (final boolean p_negated, final IPath...p_path)
final String toString ()
final Stream< ITrigger > trigger ()
final T update (final T p_agent)
final Stream< IView< T > > walk (final IPath p_path, final IViewGenerator< T >...p_generator)
Private Member Functions
IView< T > leafview (final Stream< IView< T >> p_stream)
returns the leaf of a view path
final Stream< IView< T > > walkdown (final IPath p_path, final IViewGenerator< T >...p_generator)
inner walking structure of views
Private Attributes
final IBeliefbase< T > m_beliefbase
reference to the beliefbase context
final String m_name
view name
final IView< T > m_parent
parent name
Detailed Description
Template Parameters
T agent type
Definition at line 46 of file CView.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.CView (final String p_name, final IBeliefbase< T > p_beliefbase)
Parameters
p_name view name
p_beliefbase reference to the beliefbase context
Definition at line 69 of file CView.java.
org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.CView (final String p_name, final IBeliefbase< T > p_beliefbase, final IView< T > p_parent)
Parameters
p_name view name
p_beliefbase reference to the beliefbase context
p_parent reference to the parent view
Definition at line 82 of file CView.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Member Function Documentation
final IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.add (final Stream< ILiteral > p_literal)
Definition at line 120 of file CView.java.
final IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.add (final ILiteral... p_literal)
Definition at line 128 of file CView.java.
final IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.add (final IPath p_path, final IView< T >... p_view)
Definition at line 135 of file CView.java.
final IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.add (final IView< T >... p_view)
Definition at line 145 of file CView.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
final IBeliefbase<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.beliefbase ()
Definition at line 341 of file CView.java.
final IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.clear (final IPath... p_path)
Definition at line 184 of file CView.java.
final boolean org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.containsLiteral (final IPath p_path)
Definition at line 207 of file CView.java.
References org.lightjason.agentspeak.common.IPath.size().
final boolean org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.containsView (final IPath p_path)
Definition at line 196 of file CView.java.
References org.lightjason.agentspeak.common.IPath.size().
final boolean org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.empty ()
Definition at line 347 of file CView.java.
final boolean org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.equals (final Object p_object)
Definition at line 400 of file CView.java.
final IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.generate (final IViewGenerator< T > p_generator, final IPath... p_paths)
Definition at line 276 of file CView.java.
final int org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.hashCode ()
Definition at line 394 of file CView.java.
final boolean org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.hasParent ()
Definition at line 388 of file CView.java.
IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.leafview (final Stream< IView< T >> p_stream) private
Parameters
p_stream stream of views
Returns
last / leaf view
Definition at line 327 of file CView.java.
final String org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.name ()
Definition at line 368 of file CView.java.
final IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.parent ()
Definition at line 382 of file CView.java.
final IPath org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.path ()
Definition at line 374 of file CView.java.
References org.lightjason.agentspeak.common.IPath.pushfront().
final IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.remove (final IView< T > p_view)
Definition at line 163 of file CView.java.
final IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.remove (final Stream< ILiteral > p_literal)
Definition at line 170 of file CView.java.
final IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.remove (final ILiteral... p_literal)
Definition at line 178 of file CView.java.
final Stream<IView<T> > org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.root ()
Definition at line 359 of file CView.java.
final int org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.size ()
Definition at line 353 of file CView.java.
final Stream<ILiteral> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.stream (final IPath... p_path)
Definition at line 225 of file CView.java.
final Stream<ILiteral> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.stream (final boolean p_negated, final IPath... p_path)
Definition at line 247 of file CView.java.
final String org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.toString ()
Definition at line 406 of file CView.java.
final Stream<ITrigger> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.trigger ()
Definition at line 99 of file CView.java.
final T org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.update (final T p_agent)
Definition at line 108 of file CView.java.
final Stream<IView<T> > org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.walk (final IPath p_path, final IViewGenerator< T >... p_generator)
Definition at line 270 of file CView.java.
final Stream<IView<T> > org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.walkdown (final IPath p_path, final IViewGenerator< T >... p_generator) private
Parameters
p_path path
p_generator generator (first argument is used, other elements will be ignored)
Returns
view stream
Definition at line 292 of file CView.java.
References org.lightjason.agentspeak.common.IPath.getSubPath(), org.lightjason.agentspeak.common.IPath.isEmpty(), and org.lightjason.agentspeak.common.CCommon.languagestring().
Member Data Documentation
final IBeliefbase<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.m_beliefbase private
Definition at line 55 of file CView.java.
final String org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.m_name private
Definition at line 51 of file CView.java.
final IView<T> org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.m_parent private
Definition at line 59 of file CView.java.