LightJason - AgentSpeak(L++): org.lightjason.agentspeak.agent.TestCAgent Class Reference
org.lightjason.agentspeak.agent.TestCAgent Class Reference
test agent structure
Classes
class CAgent
agent class
class CAgentGenerator
agent generator class
class CAggregation
aggregation function
class CVariableBuilder
variable builder
Public Member Functions
final void testASLDefault ()
test for default generators and configuration
final void testASLManual ()
asl parsing test
Static Public Member Functions
static void main (final String[] p_args) throws Exception
manuell running test
Static Package Functions
[static initializer]
Static Private Member Functions
static Pair< Boolean, String > testAgentManual (final String p_script, final String p_name)
static function to run an agent
Static Private Attributes
static final Map< IAction, Double > ACTIONS
list with default (non-working) actions
static final Map< String, String > ASL
map with all testing asl
Detailed Description
Definition at line 65 of file TestCAgent.java.
Member Function Documentation
org.lightjason.agentspeak.agent.TestCAgent.[static initializer] () static package
static void org.lightjason.agentspeak.agent.TestCAgent.main (final String[] p_args) throws Exception static
Parameters
p_args arguments
Exceptions
Exception on parsing exception
Definition at line 152 of file TestCAgent.java.
static Pair<Boolean, String> org.lightjason.agentspeak.agent.TestCAgent.testAgentManual (final String p_script, final String p_name) static private
Parameters
p_script script path
p_name agent name
Returns
tupel & string
Definition at line 169 of file TestCAgent.java.
References org.lightjason.agentspeak.agent.TestCAgent.ACTIONS, and org.lightjason.agentspeak.language.CLiteral.from().
Referenced by org.lightjason.agentspeak.agent.TestCAgent.testASLManual().
final void org.lightjason.agentspeak.agent.TestCAgent.testASLDefault ()
Definition at line 116 of file TestCAgent.java.
References org.lightjason.agentspeak.agent.TestCAgent.ACTIONS, and org.lightjason.agentspeak.language.score.IAggregation.EMPTY.
final void org.lightjason.agentspeak.agent.TestCAgent.testASLManual ()
Definition at line 102 of file TestCAgent.java.
References org.lightjason.agentspeak.agent.TestCAgent.testAgentManual().
Member Data Documentation
final Map<IAction, Double> org.lightjason.agentspeak.agent.TestCAgent.ACTIONS static private
Definition at line 70 of file TestCAgent.java.
Referenced by org.lightjason.agentspeak.agent.TestCAgent.testAgentManual(), and org.lightjason.agentspeak.agent.TestCAgent.testASLDefault().
final Map<String, String> org.lightjason.agentspeak.agent.TestCAgent.ASL static private
Initial value:
= StreamUtils.zip(
        Stream.of(
            "src/test/resources/agent/complete.asl"
        ),
        Stream.of(
            "full-test agent"
        ),
        AbstractMap.SimpleImmutableEntry::new
    ).collect( Collectors.toMap( Map.Entry::getKey, Map.Entry::getValue ) )
Definition at line 74 of file TestCAgent.java.