LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.IContext Interface Reference
org.lightjason.agentspeak.language.execution.IContext Interface Reference
execution context with local data
Public Member Functions
IAgent<?> agent ()
returns the agent of the context
IContext duplicate ()
duplicates the context with a shallow-copy
IInstantiable instance ()
returns the instance object
Map< IPath, IVariable<?> > instancevariables ()
returns the variables names and their current value
Detailed Description
Definition at line 37 of file IContext.java.
Member Function Documentation
IAgent<?> org.lightjason.agentspeak.language.execution.IContext.agent ()
Returns
agent
Implemented in org.lightjason.agentspeak.language.execution.CContext.
Referenced by org.lightjason.agentspeak.action.buildin.generic.datetime.CCycleTime.execute(), org.lightjason.agentspeak.action.buildin.generic.agent.CBeliefList.execute(), org.lightjason.agentspeak.action.binding.CMethodAction.execute(), org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.execute(), and org.lightjason.agentspeak.language.execution.action.CLambdaExpression.getLocalContext().
IContext org.lightjason.agentspeak.language.execution.IContext.duplicate ()
Returns
shallow-copy of the context
Implemented in org.lightjason.agentspeak.language.execution.CContext.
IInstantiable org.lightjason.agentspeak.language.execution.IContext.instance ()
Returns
instance object plan or rule
Implemented in org.lightjason.agentspeak.language.execution.CContext.
Map<IPath, IVariable<?> > org.lightjason.agentspeak.language.execution.IContext.instancevariables ()
Returns
variable names and their current value
Implemented in org.lightjason.agentspeak.language.execution.CContext.