LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> > Class Reference
org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> > Class Reference
beliefbase, reference counting is used to collect the events for each beliefbase view
Inherits IBaseBeliefbase< T >.
Public Member Functions
CBeliefbasePersistent (final IStorage< ILiteral, IView< T >, T > p_storage)
ctor
final ILiteral add (final ILiteral p_literal)
final IView< T > add (final IView< T > p_view)
final IBeliefbase< T > clear ()
final boolean containsLiteral (final String p_key)
final boolean containsView (final String p_key)
final boolean empty ()
final boolean equals (final Object p_object)
final int hashCode ()
final Collection< ILiteral > literal (final String p_key)
final IView< T > remove (final IView< T > p_view)
final ILiteral remove (final ILiteral p_literal)
final int size ()
final Stream< ILiteral > streamLiteral ()
final Stream< IView< T > > streamView ()
final String toString ()
final Stream< ITrigger > trigger (final IView< T > p_view)
final T update (final T p_agent)
final IView< T > view (final String p_key)
final IView< T > viewOrDefault (final String p_key, final IView< T > p_default)
Private Attributes
final IStorage< ILiteral,
IView< T >, T > m_storage
storage with data
Detailed Description
Definition at line 42 of file CBeliefbasePersistent.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.CBeliefbasePersistent (final IStorage< ILiteral, IView< T >, T > p_storage)
Parameters
p_storage storage
Definition at line 54 of file CBeliefbasePersistent.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Member Function Documentation
final ILiteral org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.add (final ILiteral p_literal)
Definition at line 74 of file CBeliefbasePersistent.java.
References org.lightjason.agentspeak.language.ITerm.functor().
final IView<T> org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.add (final IView< T > p_view)
Definition at line 82 of file CBeliefbasePersistent.java.
final IBeliefbase<T> org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.clear ()
Definition at line 143 of file CBeliefbasePersistent.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from().
final boolean org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.containsLiteral (final String p_key)
Definition at line 105 of file CBeliefbasePersistent.java.
final boolean org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.containsView (final String p_key)
Definition at line 111 of file CBeliefbasePersistent.java.
final boolean org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.empty ()
Definition at line 162 of file CBeliefbasePersistent.java.
final boolean org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.equals (final Object p_object)
Definition at line 68 of file CBeliefbasePersistent.java.
final int org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.hashCode ()
Definition at line 62 of file CBeliefbasePersistent.java.
final Collection<ILiteral> org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.literal (final String p_key)
Definition at line 129 of file CBeliefbasePersistent.java.
final IView<T> org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.remove (final IView< T > p_view)
Definition at line 89 of file CBeliefbasePersistent.java.
final ILiteral org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.remove (final ILiteral p_literal)
Definition at line 97 of file CBeliefbasePersistent.java.
final int org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.size ()
Definition at line 168 of file CBeliefbasePersistent.java.
final Stream<ILiteral> org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.streamLiteral ()
Definition at line 183 of file CBeliefbasePersistent.java.
final Stream<IView<T> > org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.streamView ()
Definition at line 189 of file CBeliefbasePersistent.java.
final String org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.toString ()
Definition at line 195 of file CBeliefbasePersistent.java.
final Stream<ITrigger> org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.trigger (final IView< T > p_view)
Definition at line 174 of file CBeliefbasePersistent.java.
final T org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.update (final T p_agent)
Definition at line 135 of file CBeliefbasePersistent.java.
final IView<T> org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.view (final String p_key)
Definition at line 117 of file CBeliefbasePersistent.java.
final IView<T> org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.viewOrDefault (final String p_key, final IView< T > p_default)
Definition at line 123 of file CBeliefbasePersistent.java.
Member Data Documentation
final IStorage<ILiteral, IView<T>, T> org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.m_storage private
Definition at line 47 of file CBeliefbasePersistent.java.