LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.rule.CRule Class Reference
org.lightjason.agentspeak.language.instantiable.rule.CRule Class Reference
rule structure
Public Member Functions
CRule (final ILiteral p_id, final List< IExecution > p_action)
ctor
final ILiteral getIdentifier ()
returns the identifier of the rule
final IRule replaceplaceholder (final Multimap< IPath, IRule > p_rules)
replaces all placeholder objects and reinstantiate object
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
final boolean equals (final Object p_object)
IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
defines a plan-body operation
final int hashCode ()
final IContext instantiate (final IAgent<?> p_agent, final Stream< IVariable<?>> p_variable)
creates an individual execution context
double score (final IAgent<?> p_agent)
returns the scoring value of the execution structure
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Attributes
final ILiteral m_id
identifier of the rule
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
IBaseInstantiable (final List< IExecution > p_action, final Set< IAnnotation<?>> p_annotation, final int p_hash)
ctor
Protected Attributes inherited from org.lightjason.agentspeak.language.instantiable.IBaseInstantiable
final List< IExecution > m_action
action list
final Map< IAnnotation.EType,
IAnnotation<?> > m_annotation
map with annotation (enum value for getting annotation object)
Detailed Description
Definition at line 46 of file CRule.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.language.instantiable.rule.CRule.CRule (final ILiteral p_id, final List< IExecution > p_action)
Parameters
p_id literal with signature
p_action action list
Definition at line 59 of file CRule.java.
References org.lightjason.agentspeak.language.instantiable.rule.CRule.m_id.
Referenced by org.lightjason.agentspeak.language.instantiable.rule.CRule.replaceplaceholder().
Member Function Documentation
final ILiteral org.lightjason.agentspeak.language.instantiable.rule.CRule.getIdentifier ()
Returns
literal
Implements org.lightjason.agentspeak.language.instantiable.rule.IRule.
Definition at line 71 of file CRule.java.
References org.lightjason.agentspeak.language.instantiable.rule.CRule.m_id.
Referenced by org.lightjason.agentspeak.language.instantiable.rule.CRule.replaceplaceholder().
final IRule org.lightjason.agentspeak.language.instantiable.rule.CRule.replaceplaceholder (final Multimap< IPath, IRule > p_rules)
Parameters
p_rules full instantiated rules
Returns
new object instance without placeholders
Implements org.lightjason.agentspeak.language.instantiable.rule.IRule.
Definition at line 78 of file CRule.java.
References org.lightjason.agentspeak.language.instantiable.rule.CRule.CRule(), org.lightjason.agentspeak.language.instantiable.rule.CRule.getIdentifier(), org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action, and org.lightjason.agentspeak.language.instantiable.rule.CRule.m_id.
final String org.lightjason.agentspeak.language.instantiable.rule.CRule.toString ()
Definition at line 106 of file CRule.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action, and org.lightjason.agentspeak.language.instantiable.rule.CRule.m_id.
final Stream<IVariable<?> > org.lightjason.agentspeak.language.instantiable.rule.CRule.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 94 of file CRule.java.
References org.lightjason.agentspeak.language.ILiteral.annotations(), org.lightjason.agentspeak.language.instantiable.rule.CRule.m_id, and org.lightjason.agentspeak.language.CCommon.recursiveliteral().
Member Data Documentation
final ILiteral org.lightjason.agentspeak.language.instantiable.rule.CRule.m_id private
Definition at line 51 of file CRule.java.
Referenced by org.lightjason.agentspeak.language.instantiable.rule.CRule.CRule(), org.lightjason.agentspeak.language.instantiable.rule.CRule.getIdentifier(), org.lightjason.agentspeak.language.instantiable.rule.CRule.replaceplaceholder(), org.lightjason.agentspeak.language.instantiable.rule.CRule.toString(), and org.lightjason.agentspeak.language.instantiable.rule.CRule.variables().