LightJason - AgentSpeak(L++): org.lightjason.agentspeak.common.IPath Interface Reference
org.lightjason.agentspeak.common.IPath Interface Reference
interface of a path
Public Member Functions
IPath append (final IPath p_path)
appends a path at the current and returns a new object
IPath append (final String p_path)
appends a string at the current path and returns the new object
boolean endsWith (final IPath p_path)
check of a path ends with another path
String get (final int p_index)
returns an part of the path
String getPath (final String p_separator)
returns the full path as string with an individual separator
String getPath ()
returns the full path as string
String getSeparator ()
returns the separator
IPath getSubPath (final int p_fromIndex)
creates a path of the start index until the end
IPath getSubPath (final int p_fromIndex, final int p_toIndex)
creates a path of the indices
String getSuffix ()
returns the last part of the path
boolean isEmpty ()
check if the path is empty
Stream< String > parallelStream ()
parallel stream over elements
IPath pushback (final IPath p_path)
adds a path at the end
IPath pushback (final String p_path)
adds a path at the end
IPath pushfront (final String p_path)
adds a path at the front
IPath pushfront (final IPath p_path)
adds a path to the front of the path
IPath remove (final int p_index)
removes an element
IPath remove (final int p_start, final int p_end)
removes all elements from start index until end index (exclusive)
String removeSuffix ()
remove the suffix from the path
IPath reverse ()
reverse path
IPath setSeparator (final String p_separator)
sets the separator
int size ()
returns the number of path elements
boolean startsWith (final IPath p_path)
check of a path starts with another path
boolean startsWith (final String p_path)
check of a path starts with another path
Stream< String > stream ()
stream over elements
IPath toLower ()
changes all elements to lower-case
IPath toUpper ()
changes all elements to uppercase
Detailed Description
Note
implement equals with String object, so a path object can be checked to a String
Definition at line 34 of file IPath.java.
Member Function Documentation
IPath org.lightjason.agentspeak.common.IPath.append (final IPath p_path)
Parameters
p_path path
Returns
new path
Implemented in org.lightjason.agentspeak.common.CPath.
IPath org.lightjason.agentspeak.common.IPath.append (final String p_path)
Parameters
p_path string with path
Returns
new path
Implemented in org.lightjason.agentspeak.common.CPath.
boolean org.lightjason.agentspeak.common.IPath.endsWith (final IPath p_path)
Parameters
p_path path
Returns
boolean
Implemented in org.lightjason.agentspeak.common.CPath.
String org.lightjason.agentspeak.common.IPath.get (final int p_index)
Parameters
p_index index position (negativ index is element from the end)
Returns
element
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.common.CPath.startsWith().
String org.lightjason.agentspeak.common.IPath.getPath (final String p_separator)
Parameters
p_separator separator
Returns
string path
Implemented in org.lightjason.agentspeak.common.CPath.
String org.lightjason.agentspeak.common.IPath.getPath ()
Returns
string path
Implemented in org.lightjason.agentspeak.common.CPath.
String org.lightjason.agentspeak.common.IPath.getSeparator ()
Returns
separator
Implemented in org.lightjason.agentspeak.common.CPath.
IPath org.lightjason.agentspeak.common.IPath.getSubPath (final int p_fromIndex)
Parameters
p_fromIndex start index
Returns
path
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.walkdown().
IPath org.lightjason.agentspeak.common.IPath.getSubPath (final int p_fromIndex, final int p_toIndex)
Parameters
p_fromIndex start index
p_toIndex end index (exclusive) / negative values from the end
Returns
path
Implemented in org.lightjason.agentspeak.common.CPath.
String org.lightjason.agentspeak.common.IPath.getSuffix ()
Returns
string
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.language.CLiteral.deepcopysuffix(), and org.lightjason.agentspeak.language.CLiteral.shallowcopysuffix().
boolean org.lightjason.agentspeak.common.IPath.isEmpty ()
Returns
empty flag
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.walkdown().
Stream<String> org.lightjason.agentspeak.common.IPath.parallelStream ()
Returns
parallel stream
Implemented in org.lightjason.agentspeak.common.CPath.
IPath org.lightjason.agentspeak.common.IPath.pushback (final IPath p_path)
Parameters
p_path path
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
IPath org.lightjason.agentspeak.common.IPath.pushback (final String p_path)
Parameters
p_path string path
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
IPath org.lightjason.agentspeak.common.IPath.pushfront (final String p_path)
Parameters
p_path string path
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.path().
IPath org.lightjason.agentspeak.common.IPath.pushfront (final IPath p_path)
Parameters
p_path path
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
IPath org.lightjason.agentspeak.common.IPath.remove (final int p_index)
Parameters
p_index index position
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
IPath org.lightjason.agentspeak.common.IPath.remove (final int p_start, final int p_end)
Parameters
p_start start index
p_end end index (exclusive)
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
String org.lightjason.agentspeak.common.IPath.removeSuffix ()
Returns
last item of the path
Implemented in org.lightjason.agentspeak.common.CPath.
IPath org.lightjason.agentspeak.common.IPath.reverse ()
Returns
return the changed object
Implemented in org.lightjason.agentspeak.common.CPath.
IPath org.lightjason.agentspeak.common.IPath.setSeparator (final String p_separator)
Parameters
p_separator separator
Returns
path object
Implemented in org.lightjason.agentspeak.common.CPath.
int org.lightjason.agentspeak.common.IPath.size ()
Returns
size
Implemented in org.lightjason.agentspeak.common.CPath.
Referenced by org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.containsLiteral(), and org.lightjason.agentspeak.beliefbase.view.CView< T extends IAgent<?> >.containsView().
boolean org.lightjason.agentspeak.common.IPath.startsWith (final IPath p_path)
Parameters
p_path path
Returns
boolean
Implemented in org.lightjason.agentspeak.common.CPath.
boolean org.lightjason.agentspeak.common.IPath.startsWith (final String p_path)
Parameters
p_path path
Returns
boolean
Implemented in org.lightjason.agentspeak.common.CPath.
Stream<String> org.lightjason.agentspeak.common.IPath.stream ()
Returns
sequential stream
Implemented in org.lightjason.agentspeak.common.CPath.
IPath org.lightjason.agentspeak.common.IPath.toLower ()
Returns
object
Implemented in org.lightjason.agentspeak.common.CPath.
IPath org.lightjason.agentspeak.common.IPath.toUpper ()
Returns
object
Implemented in org.lightjason.agentspeak.common.CPath.