LightJason - AgentSpeak(L++): org.lightjason.agentspeak.agent.TestCUnifier Class Reference
org.lightjason.agentspeak.agent.TestCUnifier Class Reference
test for unification
Public Member Functions
final void testAnnotationHash () throws Exception
literal annotation
final void testLiteralAnnotationTraversing () throws Exception
traversion of literal annotation content
final void testLiteralValueSequentialTraversing () throws Exception
traversion of literal value content
final void testLiteralValueTraversing () throws Exception
traversion of literal value content
final void testValueHash () throws Exception
literal value hashing
Static Public Member Functions
static void main (final String[] p_args) throws Exception
manuell running test
Detailed Description
Definition at line 47 of file TestCUnifier.java.
Member Function Documentation
static void org.lightjason.agentspeak.agent.TestCUnifier.main (final String[] p_args) throws Exception static
Parameters
p_args arguments
Exceptions
Exception parser exception
Definition at line 178 of file TestCUnifier.java.
final void org.lightjason.agentspeak.agent.TestCUnifier.testAnnotationHash () throws Exception
Exceptions
Exception parser exception
Definition at line 156 of file TestCUnifier.java.
References org.lightjason.agentspeak.language.ILiteral.annotationhash().
final void org.lightjason.agentspeak.agent.TestCUnifier.testLiteralAnnotationTraversing () throws Exception
Exceptions
Exception parser exception
Definition at line 108 of file TestCUnifier.java.
final void org.lightjason.agentspeak.agent.TestCUnifier.testLiteralValueSequentialTraversing () throws Exception
Exceptions
Exception parser exeception
Definition at line 81 of file TestCUnifier.java.
References org.lightjason.agentspeak.language.CLiteral.parse().
final void org.lightjason.agentspeak.agent.TestCUnifier.testLiteralValueTraversing () throws Exception
Exceptions
Exception on parsing exception
Definition at line 56 of file TestCUnifier.java.
References org.lightjason.agentspeak.language.CLiteral.parse().
final void org.lightjason.agentspeak.agent.TestCUnifier.testValueHash () throws Exception
Exceptions
Exception parser exception
Definition at line 124 of file TestCUnifier.java.
References org.lightjason.agentspeak.language.ILiteral.valuehash().