LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.variable.CVariableEvaluate Class Reference
org.lightjason.agentspeak.language.variable.CVariableEvaluate Class Reference
structure for creating evaluate variables
Public Member Functions
CVariableEvaluate (final IVariable<?> p_variable)
ctor
CVariableEvaluate (final IVariable<?> p_variable, final List< ITerm > p_parameter)
ctor
final ITerm deepcopy (final IPath...p_prefix)
final ITerm deepcopysuffix ()
final boolean equals (final Object p_object)
final ILiteral evaluate (final IContext p_context)
evaluates the content of the variable
final IPath fqnfunctor ()
returns the full-qualified functor with path and name
final String functor ()
returns the functor without path
final IPath functorpath ()
returns the path of the functor
final int hashCode ()
final boolean hasVariable ()
checks if the literal has variables
final boolean mutex ()
returns mutex flag
final< T > T raw ()
cast to any raw value type
final String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Private Member Functions
ILiteral fromLiteral (final ILiteral p_literal, final IContext p_context)
creates the result literal from an input literal
ILiteral fromString (final String p_value, final IContext p_context)
creates the result literal from an input string
Private Attributes
final List< ITerm > m_parameter
optional parameter list
final IVariable<?> m_variable
content variable with a string or literal
Detailed Description
Definition at line 43 of file CVariableEvaluate.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.language.variable.CVariableEvaluate.CVariableEvaluate (final IVariable<?> p_variable)
Parameters
p_variable variable
Definition at line 59 of file CVariableEvaluate.java.
org.lightjason.agentspeak.language.variable.CVariableEvaluate.CVariableEvaluate (final IVariable<?> p_variable, final List< ITerm > p_parameter)
Parameters
p_variable variable
p_parameter optional parameter list
Definition at line 70 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_parameter, and org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_variable.
Member Function Documentation
final ITerm org.lightjason.agentspeak.language.variable.CVariableEvaluate.deepcopy (final IPath... p_prefix)
Definition at line 163 of file CVariableEvaluate.java.
final ITerm org.lightjason.agentspeak.language.variable.CVariableEvaluate.deepcopysuffix ()
Definition at line 169 of file CVariableEvaluate.java.
final boolean org.lightjason.agentspeak.language.variable.CVariableEvaluate.equals (final Object p_object)
Definition at line 121 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.variable.CVariableEvaluate.hashCode().
final ILiteral org.lightjason.agentspeak.language.variable.CVariableEvaluate.evaluate (final IContext p_context)
Parameters
p_context execution context
Returns
unified literal
Implements org.lightjason.agentspeak.language.variable.IVariableEvaluate.
Definition at line 85 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromLiteral(), org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromString(), and org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_variable.
final IPath org.lightjason.agentspeak.language.variable.CVariableEvaluate.fqnfunctor ()
Returns
fqn functor
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 145 of file CVariableEvaluate.java.
ILiteral org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromLiteral (final ILiteral p_literal, final IContext p_context) private
Parameters
p_literal input literal
p_context execution context
Returns
result literal
Definition at line 193 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.ITerm.fqnfunctor(), org.lightjason.agentspeak.language.ILiteral.hasAt(), org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_parameter, and org.lightjason.agentspeak.language.ILiteral.unify().
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.evaluate().
ILiteral org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromString (final String p_value, final IContext p_context) private
Parameters
p_value input string (literal functor)
p_context execution context
Returns
result literal
Definition at line 181 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_parameter.
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.evaluate().
final String org.lightjason.agentspeak.language.variable.CVariableEvaluate.functor ()
Returns
functor
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 133 of file CVariableEvaluate.java.
final IPath org.lightjason.agentspeak.language.variable.CVariableEvaluate.functorpath ()
Returns
path
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 139 of file CVariableEvaluate.java.
final int org.lightjason.agentspeak.language.variable.CVariableEvaluate.hashCode ()
Definition at line 115 of file CVariableEvaluate.java.
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.equals().
final boolean org.lightjason.agentspeak.language.variable.CVariableEvaluate.hasVariable ()
Returns
variable flag
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 151 of file CVariableEvaluate.java.
final boolean org.lightjason.agentspeak.language.variable.CVariableEvaluate.mutex ()
Returns
mutex flag
Implements org.lightjason.agentspeak.language.variable.IVariableEvaluate.
Definition at line 78 of file CVariableEvaluate.java.
final<T> T org.lightjason.agentspeak.language.variable.CVariableEvaluate.raw ()
Template Parameters
raw type
Returns
any type
Implements org.lightjason.agentspeak.language.ITerm.
Definition at line 157 of file CVariableEvaluate.java.
final String org.lightjason.agentspeak.language.variable.CVariableEvaluate.toString ()
Definition at line 127 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_parameter, and org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_variable.
Stream<IVariable<?> > org.lightjason.agentspeak.language.variable.CVariableEvaluate.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.variable.IVariableEvaluate.
Definition at line 103 of file CVariableEvaluate.java.
References org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_parameter, and org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_variable.
Member Data Documentation
final List<ITerm> org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_parameter private
Definition at line 52 of file CVariableEvaluate.java.
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.CVariableEvaluate(), org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromLiteral(), org.lightjason.agentspeak.language.variable.CVariableEvaluate.fromString(), org.lightjason.agentspeak.language.variable.CVariableEvaluate.toString(), and org.lightjason.agentspeak.language.variable.CVariableEvaluate.variables().
final IVariable<?> org.lightjason.agentspeak.language.variable.CVariableEvaluate.m_variable private
Definition at line 48 of file CVariableEvaluate.java.
Referenced by org.lightjason.agentspeak.language.variable.CVariableEvaluate.CVariableEvaluate(), org.lightjason.agentspeak.language.variable.CVariableEvaluate.evaluate(), org.lightjason.agentspeak.language.variable.CVariableEvaluate.toString(), and org.lightjason.agentspeak.language.variable.CVariableEvaluate.variables().