LightJason - AgentSpeak(L++): org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> > Class Reference
org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> > Class Reference abstract
on-demand beliefbase for creating trigger-events without any percistency
Inherits IBaseBeliefbase< T >.
Public Member Functions
ILiteral add (final ILiteral p_literal)
final IView< T > add (final IView< T > p_view)
final IBeliefbase< T > clear ()
boolean containsLiteral (final String p_key)
final boolean containsView (final String p_key)
boolean empty ()
Collection< ILiteral > literal (final String p_key)
ILiteral remove (final ILiteral p_literal)
final IView< T > remove (final IView< T > p_view)
int size ()
Stream< ILiteral > streamLiteral ()
final Stream< IView< T > > streamView ()
final IView< T > view (final String p_key)
final IView< T > viewOrDefault (final String p_key, final IView< T > p_default)
Detailed Description
Definition at line 41 of file IBeliefbaseOnDemand.java.
Member Function Documentation
ILiteral org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.add (final ILiteral p_literal)
Definition at line 63 of file IBeliefbaseOnDemand.java.
final IView<T> org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.add (final IView< T > p_view)
Definition at line 112 of file IBeliefbaseOnDemand.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
final IBeliefbase<T> org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.clear ()
Definition at line 106 of file IBeliefbaseOnDemand.java.
boolean org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.containsLiteral (final String p_key)
Definition at line 75 of file IBeliefbaseOnDemand.java.
final boolean org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.containsView (final String p_key)
Definition at line 124 of file IBeliefbaseOnDemand.java.
boolean org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.empty ()
Definition at line 45 of file IBeliefbaseOnDemand.java.
Collection<ILiteral> org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.literal (final String p_key)
Definition at line 81 of file IBeliefbaseOnDemand.java.
ILiteral org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.remove (final ILiteral p_literal)
Definition at line 69 of file IBeliefbaseOnDemand.java.
final IView<T> org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.remove (final IView< T > p_view)
Definition at line 118 of file IBeliefbaseOnDemand.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
int org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.size ()
Definition at line 51 of file IBeliefbaseOnDemand.java.
Stream<ILiteral> org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.streamLiteral ()
Definition at line 57 of file IBeliefbaseOnDemand.java.
final Stream<IView<T> > org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.streamView ()
Definition at line 100 of file IBeliefbaseOnDemand.java.
final IView<T> org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.view (final String p_key)
Definition at line 88 of file IBeliefbaseOnDemand.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
final IView<T> org.lightjason.agentspeak.beliefbase.IBeliefbaseOnDemand< T extends IAgent<?> >.viewOrDefault (final String p_key, final IView< T > p_default)
Definition at line 94 of file IBeliefbaseOnDemand.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().