LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.CTernaryOperation Class Reference
org.lightjason.agentspeak.language.execution.action.CTernaryOperation Class Reference
if-else structure
Inherits IBaseExecution< IExpression >.
Public Member Functions
CTernaryOperation (final IExpression p_expression, final IExecution p_true, final IExecution p_false)
ctor
final boolean equals (final Object p_object)
final IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
final int hashCode ()
final String toString ()
final Stream< IVariable<?> > variables ()
Private Attributes
final IExecution m_false
false execution block
final IExecution m_true
true execution block
Detailed Description
Definition at line 44 of file CTernaryOperation.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.language.execution.action.CTernaryOperation.CTernaryOperation (final IExpression p_expression, final IExecution p_true, final IExecution p_false)
Parameters
p_expression expression
p_true true execution block
p_false false execution block
Definition at line 64 of file CTernaryOperation.java.
References org.lightjason.agentspeak.language.execution.action.CTernaryOperation.m_false, and org.lightjason.agentspeak.language.execution.action.CTernaryOperation.m_true.
Member Function Documentation
final boolean org.lightjason.agentspeak.language.execution.action.CTernaryOperation.equals (final Object p_object)
Definition at line 94 of file CTernaryOperation.java.
References org.lightjason.agentspeak.language.execution.action.CTernaryOperation.hashCode().
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CTernaryOperation.execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
Definition at line 73 of file CTernaryOperation.java.
References org.lightjason.agentspeak.language.execution.IExecution.execute(), and org.lightjason.agentspeak.language.execution.action.CTernaryOperation.m_false.
final int org.lightjason.agentspeak.language.execution.action.CTernaryOperation.hashCode ()
Definition at line 88 of file CTernaryOperation.java.
References org.lightjason.agentspeak.language.execution.action.CTernaryOperation.m_true.
Referenced by org.lightjason.agentspeak.language.execution.action.CTernaryOperation.equals().
final String org.lightjason.agentspeak.language.execution.action.CTernaryOperation.toString ()
Definition at line 100 of file CTernaryOperation.java.
References org.lightjason.agentspeak.language.execution.action.CTernaryOperation.m_false, and org.lightjason.agentspeak.language.execution.action.CTernaryOperation.m_true.
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.CTernaryOperation.variables ()
Definition at line 106 of file CTernaryOperation.java.
References org.lightjason.agentspeak.language.execution.action.CTernaryOperation.m_false, and org.lightjason.agentspeak.language.execution.IExecution.variables().
Member Data Documentation
final IExecution org.lightjason.agentspeak.language.execution.action.CTernaryOperation.m_false private
Definition at line 54 of file CTernaryOperation.java.
Referenced by org.lightjason.agentspeak.language.execution.action.CTernaryOperation.CTernaryOperation(), org.lightjason.agentspeak.language.execution.action.CTernaryOperation.execute(), org.lightjason.agentspeak.language.execution.action.CTernaryOperation.toString(), and org.lightjason.agentspeak.language.execution.action.CTernaryOperation.variables().
final IExecution org.lightjason.agentspeak.language.execution.action.CTernaryOperation.m_true private
Definition at line 50 of file CTernaryOperation.java.
Referenced by org.lightjason.agentspeak.language.execution.action.CTernaryOperation.CTernaryOperation(), org.lightjason.agentspeak.language.execution.action.CTernaryOperation.hashCode(), and org.lightjason.agentspeak.language.execution.action.CTernaryOperation.toString().