LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger Class Reference
org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger Class Reference
event with literal data
Public Member Functions
CTrigger (final EType p_event, final ILiteral p_literal)
ctor
final int contenthash ()
returns a hash value over the whole content
final boolean equals (final Object p_object)
final ILiteral getLiteral ()
returns the literal of the event
final EType getType ()
returns the type of the event
final int getVariableSize ()
returns variable number
final int hashCode ()
final ITrigger shallowcopy (final IPath...p_prefix)
final ITrigger shallowcopysuffix ()
final String toString ()
Static Public Member Functions
static ITrigger from (final EType p_event, final ILiteral p_literal)
creates a trigger event^
Private Attributes
final int m_contenthash
content hashcode
final EType m_event
event type
final int m_hashcode
hashcode
final ILiteral m_literal
literal with unified variables
final int m_variables
variable number
Detailed Description
Definition at line 37 of file CTrigger.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger (final EType p_event, final ILiteral p_literal)
Parameters
p_event type
p_literal literal with unified variables
Bug:
hash code function does not match of trigger with equal number of arguments but different argument values
Definition at line 68 of file CTrigger.java.
References org.lightjason.agentspeak.language.ITerm.fqnfunctor(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_contenthash, org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_event, org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_hashcode, org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_literal, and org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_variables.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopy(), and org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopysuffix().
Member Function Documentation
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.contenthash ()
Returns
content hash value
Implements org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.
Definition at line 129 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_contenthash.
final boolean org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.equals (final Object p_object)
Definition at line 99 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.hashCode().
static ITrigger org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from (final EType p_event, final ILiteral p_literal) static
Parameters
p_event event
p_literal trigger literal
Returns
trigger object
Definition at line 87 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger().
Referenced by org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.active(), org.lightjason.agentspeak.beliefbase.CBeliefbasePersistent< T extends IAgent<?> >.clear(), org.lightjason.agentspeak.beliefbase.IBaseBeliefbase< T extends IAgent<?> >.event(), org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementGoalLiteral.execute(), org.lightjason.agentspeak.language.execution.action.achievement_test.CAchievementGoalVariable.execute(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.execute().
final ILiteral org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.getLiteral ()
Returns
literal
Implements org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.
Definition at line 117 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_literal.
final EType org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.getType ()
Returns
type
Implements org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.
Definition at line 111 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_event.
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.getVariableSize ()
Returns
number
Implements org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.
Definition at line 123 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_variables.
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.hashCode ()
Definition at line 93 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_hashcode.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.equals().
final ITrigger org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopy (final IPath... p_prefix)
Definition at line 135 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_event, and org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_literal.
final ITrigger org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopysuffix ()
Definition at line 141 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_event, and org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_literal.
final String org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.toString ()
Definition at line 105 of file CTrigger.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_event, and org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_literal.
Member Data Documentation
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_contenthash private
Definition at line 58 of file CTrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.contenthash(), and org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger().
final EType org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_event private
Definition at line 50 of file CTrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.getType(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopy(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopysuffix(), and org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.toString().
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_hashcode private
Definition at line 54 of file CTrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger(), and org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.hashCode().
final ILiteral org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_literal private
Definition at line 46 of file CTrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.getLiteral(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopy(), org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.shallowcopysuffix(), and org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.toString().
final int org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.m_variables private
Definition at line 42 of file CTrigger.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.CTrigger(), and org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.getVariableSize().