LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.buildin.rest.IBaseRest Class Reference
org.lightjason.agentspeak.action.buildin.rest.IBaseRest Class Reference abstract
base class to read data from the restful service
Public Member Functions
final int minimalArgumentNumber ()
minimum number of arguments
Public Member Functions inherited from org.lightjason.agentspeak.action.buildin.IBuildinAction
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final double score (final IAgent<?> p_agent)
returns the scoring value of the execution structure
final String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.IExecution
IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
defines a plan-body operation
Static Protected Member Functions
static ITerm baseliteral (final Stream< String > p_functor, final Stream< ITerm > p_values)
creates a literal structure from a stream of string elements, the string stream will be build in a tree structure
static Stream< ITerm > flatterm (final Object p_object)
converts an object into a term stream
static< T > T json (final String p_url, final Class< T > p_class) throws IOException
reads a json structure from an url
static Map< String,?> xml (final String p_url) throws IOException
reads a xml structure from an url
Static Private Member Functions
static Stream< ITerm > flatcollection (final Collection<?> p_collection)
transforms a collection into a term stream
static Stream< ITerm > flatmap (final Map< String,?> p_map)
transformas a map into a literal
static String httpdata (final String p_url) throws IOException
creates a HTTP connection and reads the data
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.action.buildin.IBuildinAction
IBuildinAction ()
ctor
IBuildinAction (final int p_length)
ctor
Static Protected Attributes inherited from org.lightjason.agentspeak.action.buildin.IBuildinAction
static final Logger LOGGER = CCommon.logger(IBuildinAction.class)
logger
Detailed Description
Note
all action which inherits this class uses the system property "http.agent" for defining the http user-agent
Definition at line 56 of file IBaseRest.java.
Member Function Documentation
static ITerm org.lightjason.agentspeak.action.buildin.rest.IBaseRest.baseliteral (final Stream< String > p_functor, final Stream< ITerm > p_values) static protected
Parameters
p_functor stream with functor strings
p_values value stream
Returns
term
Definition at line 135 of file IBaseRest.java.
References org.lightjason.agentspeak.language.CLiteral.from().
Referenced by org.lightjason.agentspeak.action.buildin.rest.CXMLObject.execute(), and org.lightjason.agentspeak.action.buildin.rest.CJsonObject.execute().
static Stream<ITerm> org.lightjason.agentspeak.action.buildin.rest.IBaseRest.flatcollection (final Collection<?> p_collection) static private
Parameters
p_collection collection
Returns
term stream
Definition at line 187 of file IBaseRest.java.
References org.lightjason.agentspeak.action.buildin.rest.IBaseRest.flatterm().
Referenced by org.lightjason.agentspeak.action.buildin.rest.IBaseRest.flatterm().
static Stream<ITerm> org.lightjason.agentspeak.action.buildin.rest.IBaseRest.flatmap (final Map< String,?> p_map) static private
Parameters
p_map input map
Returns
term stream
Definition at line 169 of file IBaseRest.java.
References org.lightjason.agentspeak.action.buildin.rest.IBaseRest.flatterm().
Referenced by org.lightjason.agentspeak.action.buildin.rest.IBaseRest.flatterm().
static Stream<ITerm> org.lightjason.agentspeak.action.buildin.rest.IBaseRest.flatterm (final Object p_object) static protected
Parameters
p_object object
Returns
term stream
Definition at line 154 of file IBaseRest.java.
References org.lightjason.agentspeak.action.buildin.rest.IBaseRest.flatcollection(), and org.lightjason.agentspeak.action.buildin.rest.IBaseRest.flatmap().
Referenced by org.lightjason.agentspeak.action.buildin.rest.CXMLObject.execute(), org.lightjason.agentspeak.action.buildin.rest.CJsonObject.execute(), org.lightjason.agentspeak.action.buildin.rest.CJsonList.execute(), org.lightjason.agentspeak.action.buildin.rest.IBaseRest.flatcollection(), and org.lightjason.agentspeak.action.buildin.rest.IBaseRest.flatmap().
static String org.lightjason.agentspeak.action.buildin.rest.IBaseRest.httpdata (final String p_url) throws IOException static private
Parameters
p_url url
Returns
url data
Exceptions
IOException is thrown on connection errors
Definition at line 98 of file IBaseRest.java.
References org.lightjason.agentspeak.common.CCommon.configuration(), and org.lightjason.agentspeak.common.CCommon.PACKAGEROOT.
static <T> T org.lightjason.agentspeak.action.buildin.rest.IBaseRest.json (final String p_url, final Class< T > p_class) throws IOException static protected
Parameters
p_url url
p_class convert class type
Returns
data object
Exceptions
IOException is thrown on io errors
Definition at line 73 of file IBaseRest.java.
final int org.lightjason.agentspeak.action.buildin.rest.IBaseRest.minimalArgumentNumber ()
Returns
number of minimal arguments
Implements org.lightjason.agentspeak.action.IAction.
Definition at line 60 of file IBaseRest.java.
static Map<String, ?> org.lightjason.agentspeak.action.buildin.rest.IBaseRest.xml (final String p_url) throws IOException static protected
Parameters
p_url url
Returns
map with xml data
Exceptions
IOException is thrown on io errors
Definition at line 86 of file IBaseRest.java.