LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.buildin.math.linearprogram.IConstraint Class Reference
org.lightjason.agentspeak.action.buildin.math.linearprogram.IConstraint Class Reference abstract
abstract class for constraint actions
Protected Member Functions
IConstraint ()
ctor
final Relationship getRelation (final String p_symbol)
returns the enum of a relationship by a string value
Protected Member Functions inherited from org.lightjason.agentspeak.action.buildin.IBuildinAction
IBuildinAction ()
ctor
IBuildinAction (final int p_length)
ctor
Additional Inherited Members
Public Member Functions inherited from org.lightjason.agentspeak.action.buildin.IBuildinAction
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final double score (final IAgent<?> p_agent)
returns the scoring value of the execution structure
final String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Public Member Functions inherited from org.lightjason.agentspeak.action.IAction
int minimalArgumentNumber ()
minimum number of arguments
Public Member Functions inherited from org.lightjason.agentspeak.language.execution.IExecution
IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
defines a plan-body operation
Static Protected Attributes inherited from org.lightjason.agentspeak.action.buildin.IBuildinAction
static final Logger LOGGER = CCommon.logger(IBuildinAction.class)
logger
Detailed Description
Definition at line 37 of file IConstraint.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.action.buildin.math.linearprogram.IConstraint.IConstraint () protected
Definition at line 43 of file IConstraint.java.
Member Function Documentation
final Relationship org.lightjason.agentspeak.action.buildin.math.linearprogram.IConstraint.getRelation (final String p_symbol) protected
Parameters
p_symbol string symbol
Returns
relationship
Definition at line 54 of file IConstraint.java.
References org.lightjason.agentspeak.common.CCommon.languagestring().
Referenced by org.lightjason.agentspeak.action.buildin.math.linearprogram.CValueConstraint.execute(), and org.lightjason.agentspeak.action.buildin.math.linearprogram.CEquationConstraint.execute().