LightJason - AgentSpeak(L++): org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor Class Reference
org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor Class Reference
AST visitor class.
Inherits VoidVisitorAdapter< Object >.
Public Member Functions
void visit (final PackageDeclaration p_package, final Object p_arg)
void visit (final ClassOrInterfaceDeclaration p_class, final Object p_arg)
void visit (final EnumDeclaration p_enum, final Object p_arg)
void visit (final MethodCallExpr p_methodcall, final Object p_arg)
Package Functions
final Set< String > labels ()
returns the translated labels
Private Member Functions
String label (final String p_line)
gets the class name and label name
Static Private Member Functions
static String buildlabel (final String p_package, final String p_outerclass1, final String p_outerclass2, final String p_innerclass, final String p_label)
returns full qualified class name (inner & outer class)
Private Attributes
String m_innerclass = ""
inner class name *
Set< String > m_label = new HashSet<>()
label set
String m_outerclass = ""
outer class name *
String m_package = ""
package name *
Static Private Attributes
static final Pattern LANGUAGEMETHODPATTERN = Pattern.compile(TRANSLATEMETHODNAME + ".+?\\)")
reg expression to extract label data
static final String TRANSLATEMETHODNAME = "CCommon.languagestring"
method to translate strings
Detailed Description
Definition at line 306 of file TestCLanguageLabels.java.
Member Function Documentation
static String org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.buildlabel (final String p_package, final String p_outerclass1, final String p_outerclass2, final String p_innerclass, final String p_label) static private
Parameters
p_package package name
p_outerclass1 outer class readed value
p_outerclass2 outer class fixed value
p_innerclass inner class
p_label label (only firat element is used)
Returns
full-qualified class name
Definition at line 425 of file TestCLanguageLabels.java.
References org.lightjason.agentspeak.TestCLanguageLabels.CLASSSEPARATOR.
Referenced by org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.label().
String org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.label (final String p_line) private
Parameters
p_line input trimmed line
Returns
label or empty string
Definition at line 392 of file TestCLanguageLabels.java.
References org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.buildlabel(), org.lightjason.agentspeak.TestCLanguageLabels.CLASSSEPARATOR, org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_innerclass, org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_outerclass, org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_package, org.lightjason.agentspeak.common.CCommon.PACKAGEROOT, and org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.TRANSLATEMETHODNAME.
final Set<String> org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.labels () package
Returns
set with labels
Definition at line 338 of file TestCLanguageLabels.java.
References org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_label.
void org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.visit (final PackageDeclaration p_package, final Object p_arg)
Definition at line 344 of file TestCLanguageLabels.java.
References org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_package.
void org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.visit (final ClassOrInterfaceDeclaration p_class, final Object p_arg)
Definition at line 351 of file TestCLanguageLabels.java.
References org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_innerclass, and org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_outerclass.
void org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.visit (final EnumDeclaration p_enum, final Object p_arg)
Definition at line 364 of file TestCLanguageLabels.java.
References org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_innerclass, and org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_outerclass.
void org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.visit (final MethodCallExpr p_methodcall, final Object p_arg)
Definition at line 377 of file TestCLanguageLabels.java.
References org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_label.
Member Data Documentation
final Pattern org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.LANGUAGEMETHODPATTERN = Pattern.compile(TRANSLATEMETHODNAME + ".+?\\)") static private
Definition at line 315 of file TestCLanguageLabels.java.
String org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_innerclass = "" private
Definition at line 319 of file TestCLanguageLabels.java.
Referenced by org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.label(), and org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.visit().
Set<String> org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_label = new HashSet<>() private
Definition at line 331 of file TestCLanguageLabels.java.
Referenced by org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.labels(), and org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.visit().
String org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_outerclass = "" private
Definition at line 323 of file TestCLanguageLabels.java.
Referenced by org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.label(), and org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.visit().
String org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.m_package = "" private
Definition at line 327 of file TestCLanguageLabels.java.
Referenced by org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.label(), and org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.visit().
final String org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.TRANSLATEMETHODNAME = "CCommon.languagestring" static private
Definition at line 311 of file TestCLanguageLabels.java.
Referenced by org.lightjason.agentspeak.TestCLanguageLabels.CJavaVistor.label().