LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.expression.CAtom Class Reference
org.lightjason.agentspeak.language.execution.expression.CAtom Class Reference
atom expression
Public Member Functions
final boolean equals (final Object p_object)
final IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
defines a plan-body operation
final int hashCode ()
final double score (final IAgent<?> p_agent)
returns the scoring value of the execution structure
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Package Functions
public< T > CAtom (final T p_value)
ctor
Private Attributes
final ITerm m_value
value
Detailed Description
Definition at line 42 of file CAtom.java.
Constructor & Destructor Documentation
public<T> org.lightjason.agentspeak.language.execution.expression.CAtom.CAtom (final T p_value) package
Parameters
p_value any atomic value
Definition at line 55 of file CAtom.java.
References org.lightjason.agentspeak.language.execution.expression.CAtom.m_value.
Member Function Documentation
final boolean org.lightjason.agentspeak.language.execution.expression.CAtom.equals (final Object p_object)
Definition at line 92 of file CAtom.java.
References org.lightjason.agentspeak.language.execution.expression.CAtom.hashCode().
final IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.expression.CAtom.execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
Parameters
p_context current execution context
p_parallel parallel execution
p_argument parameter of the action
p_return return values
p_annotation annotation
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 62 of file CAtom.java.
References org.lightjason.agentspeak.language.execution.expression.CAtom.m_value, and org.lightjason.agentspeak.language.execution.expression.CAtom.toString().
final int org.lightjason.agentspeak.language.execution.expression.CAtom.hashCode ()
Definition at line 86 of file CAtom.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.CAtom.equals().
final double org.lightjason.agentspeak.language.execution.expression.CAtom.score (final IAgent<?> p_agent)
Parameters
p_agent agent for which calculates the score value
Returns
score value
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 72 of file CAtom.java.
final String org.lightjason.agentspeak.language.execution.expression.CAtom.toString ()
Definition at line 98 of file CAtom.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.CAtom.execute().
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.expression.CAtom.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 78 of file CAtom.java.
References org.lightjason.agentspeak.language.execution.expression.CAtom.m_value.
Member Data Documentation
final ITerm org.lightjason.agentspeak.language.execution.expression.CAtom.m_value private
Definition at line 47 of file CAtom.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.CAtom.CAtom(), org.lightjason.agentspeak.language.execution.expression.CAtom.execute(), and org.lightjason.agentspeak.language.execution.expression.CAtom.variables().