LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.expression.EOperator Enum Reference
org.lightjason.agentspeak.language.execution.expression.EOperator Enum Reference
expression operator
Public Member Functions
EOperator (final String p_name)
ctor
final boolean isAdditive ()
check of a additive operator
final boolean isBinary ()
check of a binary operator
final boolean isComparable ()
check of a comparable operator
final boolean isLogical ()
check of a logical operator
final boolean isMultiplicative ()
check of a multiplicative operator
final boolean isNumerical ()
check of a numeric operator
final boolean isPower ()
check of a power operator
final boolean isRelational ()
check of a relational operator
final boolean isUnary ()
check of a unary operator
final String toString ()
Public Attributes
AND =("&&")
DIVIDE =("/")
EQUAL =("==")
GREATER =(">")
GREATEREQUAL =(">=")
LESS =("<")
LESSEQUAL =("<=")
MINUS =("-")
MODULO =("%")
MULTIPLY =("*")
NEGATION =("~")
NOTEQUAL =("\\==")
OR =("||")
PLUS =("+")
POWER =("**")
XOR =("^")
Private Attributes
final String m_name
text name of the enum
Detailed Description
Definition at line 30 of file EOperator.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.language.execution.expression.EOperator.EOperator (final String p_name)
Parameters
p_name text name
Definition at line 66 of file EOperator.java.
Member Function Documentation
final boolean org.lightjason.agentspeak.language.execution.expression.EOperator.isAdditive ()
Returns
boolean for additive operator
Definition at line 122 of file EOperator.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.numerical.CAdditive.CAdditive().
final boolean org.lightjason.agentspeak.language.execution.expression.EOperator.isBinary ()
Returns
boolean of binary flag
Definition at line 152 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CCommon.createLogicalBinaryExpression(), and org.lightjason.agentspeak.language.execution.expression.IBaseBinary.IBaseBinary().
final boolean org.lightjason.agentspeak.language.execution.expression.EOperator.isComparable ()
Returns
boolean for comparable operator
Definition at line 102 of file EOperator.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.numerical.CComparable.CComparable().
final boolean org.lightjason.agentspeak.language.execution.expression.EOperator.isLogical ()
Returns
boolean for logical operator
Definition at line 82 of file EOperator.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.logical.CBinary.CBinary(), org.lightjason.agentspeak.grammar.CCommon.createLogicalBinaryExpression(), and org.lightjason.agentspeak.language.execution.expression.logical.CUnary.CUnary().
final boolean org.lightjason.agentspeak.language.execution.expression.EOperator.isMultiplicative ()
Returns
boolean for multiplicative operator
Definition at line 132 of file EOperator.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.numerical.CMultiplicative.CMultiplicative().
final boolean org.lightjason.agentspeak.language.execution.expression.EOperator.isNumerical ()
Returns
boolean for numeric operator
Definition at line 92 of file EOperator.java.
final boolean org.lightjason.agentspeak.language.execution.expression.EOperator.isPower ()
Returns
boolean for power operator
Definition at line 142 of file EOperator.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.numerical.CPower.CPower().
final boolean org.lightjason.agentspeak.language.execution.expression.EOperator.isRelational ()
Returns
boolean for relational operator
Definition at line 112 of file EOperator.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.numerical.CRelational.CRelational().
final boolean org.lightjason.agentspeak.language.execution.expression.EOperator.isUnary ()
Returns
boolean of unary operator
Definition at line 162 of file EOperator.java.
Referenced by org.lightjason.agentspeak.language.execution.expression.IBaseUnary.IBaseUnary().
final String org.lightjason.agentspeak.language.execution.expression.EOperator.toString ()
Definition at line 72 of file EOperator.java.
Member Data Documentation
org.lightjason.agentspeak.language.execution.expression.EOperator.AND =("&&")
Definition at line 42 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_logical_and(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_logical_and(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_logical_and().
org.lightjason.agentspeak.language.execution.expression.EOperator.DIVIDE =("/")
Definition at line 36 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_multiplicative(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_multiplicative(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_multiplicative().
org.lightjason.agentspeak.language.execution.expression.EOperator.EQUAL =("==")
Definition at line 46 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric().
org.lightjason.agentspeak.language.execution.expression.EOperator.GREATER =(">")
Definition at line 51 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_relation(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_relation(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_relation().
org.lightjason.agentspeak.language.execution.expression.EOperator.GREATEREQUAL =(">=")
Definition at line 52 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_relation(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_relation(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_relation().
org.lightjason.agentspeak.language.execution.expression.EOperator.LESS =("<")
Definition at line 49 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_relation(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_relation(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_relation().
org.lightjason.agentspeak.language.execution.expression.EOperator.LESSEQUAL =("<=")
Definition at line 50 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_relation(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_relation(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_relation().
final String org.lightjason.agentspeak.language.execution.expression.EOperator.m_name private
Definition at line 59 of file EOperator.java.
org.lightjason.agentspeak.language.execution.expression.EOperator.MINUS =("-")
Definition at line 33 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_additive(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_additive(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_additive().
org.lightjason.agentspeak.language.execution.expression.EOperator.MODULO =("%")
Definition at line 37 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_multiplicative(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_multiplicative(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_multiplicative().
org.lightjason.agentspeak.language.execution.expression.EOperator.MULTIPLY =("*")
Definition at line 35 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_multiplicative(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_multiplicative(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_multiplicative().
org.lightjason.agentspeak.language.execution.expression.EOperator.NEGATION =("~")
Definition at line 44 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_logical_negation(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_logical_negation(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_logical_negation().
org.lightjason.agentspeak.language.execution.expression.EOperator.NOTEQUAL =("\\==")
Definition at line 47 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric().
org.lightjason.agentspeak.language.execution.expression.EOperator.OR =("||")
Definition at line 41 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression().
org.lightjason.agentspeak.language.execution.expression.EOperator.PLUS =("+")
Definition at line 32 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_additive(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_additive(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_additive().
org.lightjason.agentspeak.language.execution.expression.EOperator.POWER =("**")
Definition at line 38 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_numeric_power(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_numeric_power(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_numeric_power().
org.lightjason.agentspeak.language.execution.expression.EOperator.XOR =("^")
Definition at line 43 of file EOperator.java.
Referenced by org.lightjason.agentspeak.grammar.CASTVisitorType.visitExpression_logical_xor(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitExpression_logical_xor(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitExpression_logical_xor().