LightJason - AgentSpeak(L++): org.lightjason.agentspeak.common.CPath Class Reference
org.lightjason.agentspeak.common.CPath Class Reference
class to create a path structure
Public Member Functions
CPath (final IPath p_path, final String...p_varargs)
copy-ctor with arguments
CPath (final IPath p_path)
copy-ctor
CPath (final String...p_varargs)
ctor
CPath (final Stream< String > p_stream)
ctor
final IPath append (final IPath p_path)
appends a path at the current and returns a new object
final IPath append (final String p_path)
appends a string at the current path and returns the new object
final int compareTo (final IPath p_path)
final synchronized boolean endsWith (final IPath p_path)
check of a path ends with another path
final boolean equals (final Object p_object)
final String get (final int p_index)
returns an part of the path
final String getPath (final String p_separator)
returns the full path as string with an individual separator
final String getPath ()
returns the full path as string
final String getSeparator ()
returns the separator
final IPath getSubPath (final int p_fromIndex)
creates a path of the start index until the end
final IPath getSubPath (final int p_fromIndex, final int p_toIndex)
creates a path of the indices
final synchronized String getSuffix ()
returns the last part of the path
final int hashCode ()
final boolean isEmpty ()
check if the path is empty
final Stream< String > parallelStream ()
parallel stream over elements
final IPath pushback (final IPath p_path)
adds a path at the end
final IPath pushback (final String p_path)
adds a path at the end
final IPath pushfront (final String p_path)
adds a path at the front
final synchronized IPath pushfront (final IPath p_path)
adds a path to the front of the path
final IPath remove (final int p_index)
removes an element
final IPath remove (final int p_start, final int p_end)
removes all elements from start index until end index (exclusive)
final String removeSuffix ()
remove the suffix from the path
final IPath reverse ()
reverse path
final IPath setSeparator (final String p_separator)
sets the separator
final int size ()
returns the number of path elements
final boolean startsWith (final IPath p_path)
check of a path starts with another path
final boolean startsWith (final String p_path)
check of a path starts with another path
final Stream< String > stream ()
stream over elements
final synchronized IPath toLower ()
changes all elements to lower-case
final String toString ()
final synchronized IPath toUpper ()
changes all elements to uppercase
Static Public Member Functions
static IPath createPath (final String...p_varargs)
creates a path object from different items
static IPath createPathWithSeperator (final String...p_varargs)
creates a path object by splitting a string
static IPath from (final String p_string)
factor method to build path
Static Public Attributes
static final String DEFAULTSEPERATOR = "/"
static final IPath EMPTY = new CPath()
empty path
Private Member Functions
CPath ()
private ctor for empty path
synchronized void normalize ()
normalize the internal path
Static Private Member Functions
static Collector< String, List
< String >, List< String > > collectorfactory ()
collector factory
static List< String > listfactory ()
list factory
Private Attributes
final List< String > m_path
list with path parts *
String m_separator = DEFAULTSEPERATOR
separator of the path elements *
Detailed Description
Definition at line 48 of file CPath.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.common.CPath.CPath (final IPath p_path, final String... p_varargs)
Parameters
p_path path object
p_varargs string arguments
Definition at line 70 of file CPath.java.
org.lightjason.agentspeak.common.CPath.CPath (final IPath p_path)
Parameters
p_path path object
Definition at line 82 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.collectorfactory(), org.lightjason.agentspeak.common.CPath.m_path, and org.lightjason.agentspeak.common.CPath.m_separator.
org.lightjason.agentspeak.common.CPath.CPath (final String... p_varargs)
Parameters
p_varargs path component
Definition at line 93 of file CPath.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), org.lightjason.agentspeak.common.CPath.m_path, and org.lightjason.agentspeak.common.CPath.m_separator.
org.lightjason.agentspeak.common.CPath.CPath (final Stream< String > p_stream)
Parameters
p_stream string collection
Definition at line 114 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_path.
org.lightjason.agentspeak.common.CPath.CPath () private
Definition at line 123 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_path.
Referenced by org.lightjason.agentspeak.common.CPath.append(), org.lightjason.agentspeak.common.CPath.createPath(), org.lightjason.agentspeak.common.CPath.createPathWithSeperator(), org.lightjason.agentspeak.common.CPath.getSubPath(), org.lightjason.agentspeak.common.CPath.pushback(), org.lightjason.agentspeak.common.CPath.pushfront(), and org.lightjason.agentspeak.common.CPath.startsWith().
Member Function Documentation
final IPath org.lightjason.agentspeak.common.CPath.append (final IPath p_path)
Parameters
p_path path
Returns
new path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 171 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath().
final IPath org.lightjason.agentspeak.common.CPath.append (final String p_path)
Parameters
p_path string with path
Returns
new path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 177 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath().
static Collector<String, List<String>, List<String> > org.lightjason.agentspeak.common.CPath.collectorfactory () static private
Returns
collector
Definition at line 433 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.CPath().
final int org.lightjason.agentspeak.common.CPath.compareTo (final IPath p_path)
Definition at line 394 of file CPath.java.
static IPath org.lightjason.agentspeak.common.CPath.createPath (final String... p_varargs) static
Parameters
p_varargs list of strings
Returns
path object
Definition at line 134 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath(), and org.lightjason.agentspeak.common.CCommon.languagestring().
static IPath org.lightjason.agentspeak.common.CPath.createPathWithSeperator (final String... p_varargs) static
Parameters
p_varargs list of string (first element is the seperator)
Returns
path object
Definition at line 148 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath(), org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.common.CPath.stream().
Referenced by org.lightjason.agentspeak.common.CPath.from().
final synchronized boolean org.lightjason.agentspeak.common.CPath.endsWith (final IPath p_path)
Parameters
p_path path
Returns
boolean
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 197 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.size().
final boolean org.lightjason.agentspeak.common.CPath.equals (final Object p_object)
Definition at line 295 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.hashCode().
Referenced by org.lightjason.agentspeak.common.CPath.normalize(), and org.lightjason.agentspeak.common.CPath.startsWith().
static IPath org.lightjason.agentspeak.common.CPath.from (final String p_string) static
Parameters
p_string input string
Returns
path
Definition at line 165 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.createPathWithSeperator(), org.lightjason.agentspeak.common.CPath.DEFAULTSEPERATOR, and org.lightjason.agentspeak.common.CPath.EMPTY.
Referenced by org.lightjason.agentspeak.language.CLiteral.deepcopysuffix(), org.lightjason.agentspeak.action.buildin.generic.agent.CBeliefList.execute(), org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.language.CLiteral.shallowcopysuffix(), org.lightjason.agentspeak.grammar.CASTVisitorType.visitLiteral(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitLiteral(), org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitLiteral(), org.lightjason.agentspeak.grammar.CASTVisitorAgent.visitTest_action(), and org.lightjason.agentspeak.grammar.CASTVisitorPlanBundle.visitTest_action().
final String org.lightjason.agentspeak.common.CPath.get (final int p_index)
Parameters
p_index index position (negativ index is element from the end)
Returns
element
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 212 of file CPath.java.
final String org.lightjason.agentspeak.common.CPath.getPath (final String p_separator)
Parameters
p_separator separator
Returns
string path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 218 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_path.
final String org.lightjason.agentspeak.common.CPath.getPath ()
Returns
string path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 224 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_path, and org.lightjason.agentspeak.common.CPath.m_separator.
final String org.lightjason.agentspeak.common.CPath.getSeparator ()
Returns
separator
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 230 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_separator.
final IPath org.lightjason.agentspeak.common.CPath.getSubPath (final int p_fromIndex)
Parameters
p_fromIndex start index
Returns
path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 260 of file CPath.java.
final IPath org.lightjason.agentspeak.common.CPath.getSubPath (final int p_fromIndex, final int p_toIndex)
Parameters
p_fromIndex start index
p_toIndex end index (exclusive) / negative values from the end
Returns
path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 266 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath(), and org.lightjason.agentspeak.common.CPath.m_separator.
final synchronized String org.lightjason.agentspeak.common.CPath.getSuffix ()
Returns
string
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 280 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_path.
final int org.lightjason.agentspeak.common.CPath.hashCode ()
Definition at line 288 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.equals().
final boolean org.lightjason.agentspeak.common.CPath.isEmpty ()
Returns
empty flag
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 315 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.removeSuffix().
static List<String> org.lightjason.agentspeak.common.CPath.listfactory () static private
Returns
list
Definition at line 477 of file CPath.java.
synchronized void org.lightjason.agentspeak.common.CPath.normalize () private
Definition at line 402 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.equals(), and org.lightjason.agentspeak.common.CPath.m_path.
final Stream<String> org.lightjason.agentspeak.common.CPath.parallelStream ()
Returns
parallel stream
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 388 of file CPath.java.
final IPath org.lightjason.agentspeak.common.CPath.pushback (final IPath p_path)
Parameters
p_path path
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 321 of file CPath.java.
final IPath org.lightjason.agentspeak.common.CPath.pushback (final String p_path)
Parameters
p_path string path
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 328 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath().
final IPath org.lightjason.agentspeak.common.CPath.pushfront (final String p_path)
Parameters
p_path string path
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 335 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath().
final synchronized IPath org.lightjason.agentspeak.common.CPath.pushfront (final IPath p_path)
Parameters
p_path path
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 342 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_path.
final IPath org.lightjason.agentspeak.common.CPath.remove (final int p_index)
Parameters
p_index index position
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 183 of file CPath.java.
final IPath org.lightjason.agentspeak.common.CPath.remove (final int p_start, final int p_end)
Parameters
p_start start index
p_end end index (exclusive)
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 190 of file CPath.java.
final String org.lightjason.agentspeak.common.CPath.removeSuffix ()
Returns
last item of the path
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 351 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.isEmpty(), and org.lightjason.agentspeak.common.CPath.m_path.
final IPath org.lightjason.agentspeak.common.CPath.reverse ()
Returns
return the changed object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 363 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.m_path.
final IPath org.lightjason.agentspeak.common.CPath.setSeparator (final String p_separator)
Parameters
p_separator separator
Returns
path object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 236 of file CPath.java.
References org.lightjason.agentspeak.common.CCommon.languagestring(), and org.lightjason.agentspeak.common.CPath.m_separator.
final int org.lightjason.agentspeak.common.CPath.size ()
Returns
size
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 370 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.endsWith(), and org.lightjason.agentspeak.common.CPath.startsWith().
final boolean org.lightjason.agentspeak.common.CPath.startsWith (final IPath p_path)
Parameters
p_path path
Returns
boolean
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 204 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.equals(), org.lightjason.agentspeak.common.IPath.get(), and org.lightjason.agentspeak.common.CPath.size().
final boolean org.lightjason.agentspeak.common.CPath.startsWith (final String p_path)
Parameters
p_path path
Returns
boolean
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 376 of file CPath.java.
References org.lightjason.agentspeak.common.CPath.CPath().
final Stream<String> org.lightjason.agentspeak.common.CPath.stream ()
Returns
sequential stream
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 382 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.createPathWithSeperator().
final synchronized IPath org.lightjason.agentspeak.common.CPath.toLower ()
Returns
object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 246 of file CPath.java.
final String org.lightjason.agentspeak.common.CPath.toString ()
Definition at line 305 of file CPath.java.
final synchronized IPath org.lightjason.agentspeak.common.CPath.toUpper ()
Returns
object
Implements org.lightjason.agentspeak.common.IPath.
Definition at line 253 of file CPath.java.
Member Data Documentation
final String org.lightjason.agentspeak.common.CPath.DEFAULTSEPERATOR = "/" static
Definition at line 50 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.from().
final IPath org.lightjason.agentspeak.common.CPath.EMPTY = new CPath() static
Definition at line 54 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.from().
final List<String> org.lightjason.agentspeak.common.CPath.m_path private
Definition at line 58 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.CPath(), org.lightjason.agentspeak.common.CPath.getPath(), org.lightjason.agentspeak.common.CPath.getSuffix(), org.lightjason.agentspeak.common.CPath.normalize(), org.lightjason.agentspeak.common.CPath.pushfront(), org.lightjason.agentspeak.common.CPath.removeSuffix(), and org.lightjason.agentspeak.common.CPath.reverse().
String org.lightjason.agentspeak.common.CPath.m_separator = DEFAULTSEPERATOR private
Definition at line 62 of file CPath.java.
Referenced by org.lightjason.agentspeak.common.CPath.CPath(), org.lightjason.agentspeak.common.CPath.getPath(), org.lightjason.agentspeak.common.CPath.getSeparator(), org.lightjason.agentspeak.common.CPath.getSubPath(), and org.lightjason.agentspeak.common.CPath.setSeparator().