LightJason - AgentSpeak(L++): org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> > Class Reference
org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> > Class Reference abstract
agent base structure
Inherits IAgent< T >.
Public Member Functions
IBaseAgent (final IAgentConfiguration< T > p_configuration)
ctor
final IAggregation aggregation ()
final IView< T > beliefbase ()
T call () throws Exception
final long cycle ()
final long cycletime ()
final IFuzzy< Boolean, T > fuzzy ()
final< N extends IInspector >
Stream< N > inspect (final N...p_inspector)
final Multimap< ITrigger,
Triple< IPlan, AtomicLong,
AtomicLong > > plans ()
final< N extends IAgent<?> > N raw ()
final Multimap< IPath, IRule > rules ()
final Multimap< IPath, ILiteral > runningplans ()
final IAgent< T > sleep (final long p_cycles, final ITerm...p_term)
final IAgent< T > sleep (final long p_cycles, final Stream< ITerm > p_literal)
final boolean sleeping ()
final Map< String,?> storage ()
String toString ()
final IFuzzyValue< Boolean > trigger (final ITrigger p_trigger, final boolean...p_immediately)
final IUnifier unifier ()
final IVariableBuilder variablebuilder ()
final IAgent< T > wakeup (final ITerm...p_term)
final IAgent< T > wakeup (final Stream< ITerm > p_term)
Protected Attributes
final IView< T > m_beliefbase
beliefbase
final Multimap< ITrigger,
Triple< IPlan, AtomicLong,
AtomicLong > > m_plans = Multimaps.synchronizedMultimap(HashMultimap.create())
map with all existing plans and successful / fail runs
final Multimap< IPath, IRule > m_rules = Multimaps.synchronizedMultimap(LinkedHashMultimap.create())
multimap with rules
final Map< String,?> m_storage = new ConcurrentHashMap<>()
storage map
final Map< Integer, ITrigger > m_trigger = new ConcurrentHashMap<>()
execution trigger with content hash
Private Member Functions
boolean active (final boolean p_immediatly)
runs the wakeup goal
IFuzzyValue< Boolean > execute (final Collection< Pair< Triple< IPlan, AtomicLong, AtomicLong >, IContext >> p_execution)
execute list of plans
Collection< Pair< Triple
< IPlan, AtomicLong,
AtomicLong >, IContext > > generateexecution (final Stream< ITrigger > p_trigger)
create execution list with plan and context
synchronized Collection< Pair
< Triple< IPlan, AtomicLong,
AtomicLong >, IContext > > generateexecutionlist ()
create the plan executionlist with clearing internal structures
Private Attributes
final IAggregation m_aggregation
aggregation function
final AtomicLong m_cycle = new AtomicLong()
curent agent cycle
final AtomicLong m_cycletime = new AtomicLong()
nano seconds at the last cycle
final IFuzzy< Boolean, T > m_fuzzy
fuzzy result collector
final Multimap< IPath, ILiteral > m_runningplans = Multimaps.synchronizedSetMultimap(HashMultimap.create())
running plans (thread-safe)
final AtomicLong m_sleepingcycles = new AtomicLong(Long.MIN_VALUE)
number of sleeping cycles
final Set< ITerm > m_sleepingterm = Collections.synchronizedSet(new HashSet<>())
set for waking-up literals
final IUnifier m_unifier
unifier
final IVariableBuilder m_variablebuilder
variable builder
Detailed Description
Template Parameters
T agent type
Definition at line 76 of file IBaseAgent.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.IBaseAgent (final IAgentConfiguration< T > p_configuration)
Parameters
p_configuration agent configuration
Definition at line 146 of file IBaseAgent.java.
Member Function Documentation
boolean org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.active (final boolean p_immediatly) private
Parameters
p_immediatly runs the wake always
Returns
returns true if the agent is active
Definition at line 467 of file IBaseAgent.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.CTrigger.from(), and org.lightjason.agentspeak.language.CLiteral.from().
final IAggregation org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.aggregation ()
Definition at line 278 of file IBaseAgent.java.
final IView<T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.beliefbase ()
Definition at line 166 of file IBaseAgent.java.
T org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.call () throws Exception
Definition at line 344 of file IBaseAgent.java.
final long org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.cycle ()
Definition at line 260 of file IBaseAgent.java.
final long org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.cycletime ()
Definition at line 254 of file IBaseAgent.java.
IFuzzyValue<Boolean> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.execute (final Collection< Pair< Triple< IPlan, AtomicLong, AtomicLong >, IContext >> p_execution) private
Parameters
p_execution execution collection with instantiated plans and context
Returns
fuzzy result for each executaed plan
Definition at line 438 of file IBaseAgent.java.
final IFuzzy<Boolean, T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.fuzzy ()
Definition at line 272 of file IBaseAgent.java.
Collection<Pair<Triple<IPlan, AtomicLong, AtomicLong>, IContext> > org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.generateexecution (final Stream< ITrigger > p_trigger) private
Parameters
p_trigger trigger stream
Returns
collection with excutable plans, instantiated execution context and plan statistic
Definition at line 394 of file IBaseAgent.java.
synchronized Collection<Pair<Triple<IPlan, AtomicLong, AtomicLong>, IContext> > org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.generateexecutionlist () private
Note
must be synchronized for avoid indeterministic trigger list
Returns
collection with execution plan and context
Definition at line 373 of file IBaseAgent.java.
final<N extends IInspector> Stream<N> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.inspect (final N... p_inspector)
Definition at line 173 of file IBaseAgent.java.
final Multimap<ITrigger, Triple<IPlan, AtomicLong, AtomicLong> > org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.plans ()
Definition at line 266 of file IBaseAgent.java.
final<N extends IAgent<?> > N org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.raw ()
Definition at line 297 of file IBaseAgent.java.
final Multimap<IPath, IRule> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.rules ()
Definition at line 290 of file IBaseAgent.java.
final Multimap<IPath, ILiteral> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.runningplans ()
Definition at line 193 of file IBaseAgent.java.
final IAgent<T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.sleep (final long p_cycles, final ITerm... p_term)
Definition at line 205 of file IBaseAgent.java.
final IAgent<T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.sleep (final long p_cycles, final Stream< ITerm > p_literal)
Definition at line 216 of file IBaseAgent.java.
final boolean org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.sleeping ()
Definition at line 199 of file IBaseAgent.java.
final Map<String, ?> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.storage ()
Definition at line 242 of file IBaseAgent.java.
String org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.toString ()
Definition at line 303 of file IBaseAgent.java.
final IFuzzyValue<Boolean> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.trigger (final ITrigger p_trigger, final boolean... p_immediately)
Definition at line 321 of file IBaseAgent.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.getLiteral().
final IUnifier org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.unifier ()
Definition at line 248 of file IBaseAgent.java.
final IVariableBuilder org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.variablebuilder ()
Definition at line 284 of file IBaseAgent.java.
final IAgent<T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.wakeup (final ITerm... p_term)
Definition at line 224 of file IBaseAgent.java.
final IAgent<T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.wakeup (final Stream< ITerm > p_term)
Definition at line 234 of file IBaseAgent.java.
Member Data Documentation
final IAggregation org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_aggregation private
Definition at line 126 of file IBaseAgent.java.
final IView<T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_beliefbase protected
Definition at line 81 of file IBaseAgent.java.
final AtomicLong org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_cycle = new AtomicLong() private
Definition at line 103 of file IBaseAgent.java.
final AtomicLong org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_cycletime = new AtomicLong() private
Definition at line 107 of file IBaseAgent.java.
final IFuzzy<Boolean, T> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_fuzzy private
Definition at line 134 of file IBaseAgent.java.
final Multimap<ITrigger, Triple<IPlan, AtomicLong, AtomicLong> > org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_plans = Multimaps.synchronizedMultimap(HashMultimap.create()) protected
Definition at line 99 of file IBaseAgent.java.
final Multimap<IPath, IRule> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_rules = Multimaps.synchronizedMultimap(LinkedHashMultimap.create()) protected
Definition at line 95 of file IBaseAgent.java.
final Multimap<IPath, ILiteral> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_runningplans = Multimaps.synchronizedSetMultimap(HashMultimap.create()) private
Definition at line 138 of file IBaseAgent.java.
final AtomicLong org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_sleepingcycles = new AtomicLong(Long.MIN_VALUE) private
Note
values >= 0 defines the sleeping time, Long.MAX_VALUE is infinity sleeping negative values defines the activity
Definition at line 114 of file IBaseAgent.java.
final Set<ITerm> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_sleepingterm = Collections.synchronizedSet(new HashSet<>()) private
Definition at line 118 of file IBaseAgent.java.
final Map<String, ?> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_storage = new ConcurrentHashMap<>() protected
Note
must be thread-safe
Definition at line 87 of file IBaseAgent.java.
final Map<Integer, ITrigger> org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_trigger = new ConcurrentHashMap<>() protected
Definition at line 91 of file IBaseAgent.java.
final IUnifier org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_unifier private
Definition at line 122 of file IBaseAgent.java.
final IVariableBuilder org.lightjason.agentspeak.agent.IBaseAgent< T extends IAgent<?> >.m_variablebuilder private
Definition at line 130 of file IBaseAgent.java.