LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.binding.CMethodAction Class Reference
org.lightjason.agentspeak.action.binding.CMethodAction Class Reference
action for binding a method
Public Member Functions
CMethodAction (final Method p_method) throws IllegalAccessException
ctor
IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
defines a plan-body operation
final int minimalArgumentNumber ()
minimum number of arguments
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final double score (final IAgent<?> p_agent)
returns the scoring value of the execution structure
final String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Static Private Member Functions
static IFuzzyValue< Boolean > returnvalues (final Object p_result, final List< ITerm > p_return)
creates the returns values of the execution
Private Attributes
final int m_arguments
number of arguments
final MethodHandle m_method
method handle
final IPath m_name
name of the action
Detailed Description
Note
action uses agent for object binding
Definition at line 48 of file CMethodAction.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.action.binding.CMethodAction.CMethodAction (final Method p_method) throws IllegalAccessException
Parameters
p_method method reference
Exceptions
IllegalAccessException on method access error
Definition at line 70 of file CMethodAction.java.
References org.lightjason.agentspeak.action.binding.CMethodAction.m_arguments, org.lightjason.agentspeak.action.binding.CMethodAction.m_method, org.lightjason.agentspeak.action.binding.CMethodAction.m_name, and org.lightjason.agentspeak.action.binding.CMethodAction.name().
Member Function Documentation
IFuzzyValue<Boolean> org.lightjason.agentspeak.action.binding.CMethodAction.execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
Parameters
p_context current execution context
p_parallel parallel execution
p_argument parameter of the action
p_return return values
p_annotation annotation
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 95 of file CMethodAction.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), org.lightjason.agentspeak.action.binding.CMethodAction.m_arguments, org.lightjason.agentspeak.action.binding.CMethodAction.m_method, org.lightjason.agentspeak.language.ITerm.raw(), and org.lightjason.agentspeak.action.binding.CMethodAction.returnvalues().
final int org.lightjason.agentspeak.action.binding.CMethodAction.minimalArgumentNumber ()
Returns
number of minimal arguments
Implements org.lightjason.agentspeak.action.IAction.
Definition at line 89 of file CMethodAction.java.
References org.lightjason.agentspeak.action.binding.CMethodAction.m_arguments.
final IPath org.lightjason.agentspeak.action.binding.CMethodAction.name ()
Returns
path (literal functor)
Implements org.lightjason.agentspeak.action.IAction.
Definition at line 83 of file CMethodAction.java.
References org.lightjason.agentspeak.action.binding.CMethodAction.m_name.
Referenced by org.lightjason.agentspeak.action.binding.CMethodAction.CMethodAction().
static IFuzzyValue<Boolean> org.lightjason.agentspeak.action.binding.CMethodAction.returnvalues (final Object p_result, final List< ITerm > p_return) static private
Parameters
p_result return object of the invoke call
p_return return argument list
Returns
execution return
Definition at line 131 of file CMethodAction.java.
References org.lightjason.agentspeak.action.IBaseAction.equals().
Referenced by org.lightjason.agentspeak.action.binding.CMethodAction.execute().
Member Data Documentation
final int org.lightjason.agentspeak.action.binding.CMethodAction.m_arguments private
Definition at line 57 of file CMethodAction.java.
Referenced by org.lightjason.agentspeak.action.binding.CMethodAction.CMethodAction(), org.lightjason.agentspeak.action.binding.CMethodAction.execute(), and org.lightjason.agentspeak.action.binding.CMethodAction.minimalArgumentNumber().
final MethodHandle org.lightjason.agentspeak.action.binding.CMethodAction.m_method private
Definition at line 61 of file CMethodAction.java.
Referenced by org.lightjason.agentspeak.action.binding.CMethodAction.CMethodAction(), and org.lightjason.agentspeak.action.binding.CMethodAction.execute().
final IPath org.lightjason.agentspeak.action.binding.CMethodAction.m_name private
Definition at line 53 of file CMethodAction.java.
Referenced by org.lightjason.agentspeak.action.binding.CMethodAction.CMethodAction(), and org.lightjason.agentspeak.action.binding.CMethodAction.name().