LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper Class Reference
org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper Class Reference
inner class for encapsulating action execution
Public Member Functions
final boolean equals (final Object p_object)
IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
defines a plan-body operation
final int hashCode ()
final double score (final IAgent<?> p_agent)
returns the scoring value of the execution structure
final String toString ()
final Stream< IVariable<?> > variables ()
returns a stream with all used variables
Package Functions
CActionWrapper (final ILiteral p_literal, final Map< IPath, IAction > p_actions, final Multiset< IAction > p_scorecache)
ctor
Private Member Functions
Map< Integer, IExecution > createSubExecutions (final Collection<?extends ITerm > p_elements, final Map< IPath, IAction > p_actions, final Multiset< IAction > p_scorecache)
builds the map of execution arguments
List< ITerm > subexecute (final IContext p_context, final Map< Integer, IExecution > p_execution)
execute inner structures
Private Attributes
final IAction m_action
action
final Map< Integer, IExecution > m_annotation
annotation as map with index for prevent result order on parallel execution
final Map< Integer, IExecution > m_arguments
arguments as map with index for prevent result order on parallel execution
final boolean m_parallel
parallel execution flag
Detailed Description
Warning
execution must run variable repacing before action calling
Definition at line 191 of file CProxyAction.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.CActionWrapper (final ILiteral p_literal, final Map< IPath, IAction > p_actions, final Multiset< IAction > p_scorecache) package
Parameters
p_literal action literal
p_actions actions
p_scorecache score cache
Definition at line 220 of file CProxyAction.java.
References org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_action, org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_annotation, org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_arguments, org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_parallel, and org.lightjason.agentspeak.language.ILiteral.orderedvalues().
Referenced by org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.createSubExecutions().
Member Function Documentation
Map<Integer, IExecution> org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.createSubExecutions (final Collection<?extends ITerm > p_elements, final Map< IPath, IAction > p_actions, final Multiset< IAction > p_scorecache) private
Parameters
p_elements collection with literal elements (term- / literal list of attributes & annotations)
p_actions map with actions
p_scorecache store cache
Returns
ordered execution structure
Definition at line 297 of file CProxyAction.java.
References org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.CActionWrapper().
final boolean org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.equals (final Object p_object)
Definition at line 259 of file CProxyAction.java.
References org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.hashCode().
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
Parameters
p_context current execution context
p_parallel parallel execution
p_argument parameter of the action
p_return return values
p_annotation annotation
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 265 of file CProxyAction.java.
References org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_annotation, org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_arguments, org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_parallel, and org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.subexecute().
final int org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.hashCode ()
Definition at line 247 of file CProxyAction.java.
References org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_arguments.
Referenced by org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.equals().
final double org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.score (final IAgent<?> p_agent)
Parameters
p_agent agent for which calculates the score value
Returns
score value
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 277 of file CProxyAction.java.
List<ITerm> org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.subexecute (final IContext p_context, final Map< Integer, IExecution > p_execution) private
Parameters
p_context context structure
p_execution map with execution elements
Returns
return arguments of execution (flat list)
Definition at line 317 of file CProxyAction.java.
References org.lightjason.agentspeak.language.execution.action.CProxyAction.execute().
Referenced by org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.execute().
final String org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.toString ()
Definition at line 253 of file CProxyAction.java.
References org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_action.
final Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 283 of file CProxyAction.java.
Member Data Documentation
final IAction org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_action private
Definition at line 200 of file CProxyAction.java.
Referenced by org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.CActionWrapper(), and org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.toString().
final Map<Integer, IExecution> org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_annotation private
Definition at line 210 of file CProxyAction.java.
Referenced by org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.CActionWrapper(), and org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.execute().
final Map<Integer, IExecution> org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_arguments private
Definition at line 205 of file CProxyAction.java.
Referenced by org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.CActionWrapper(), org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.execute(), and org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.hashCode().
final boolean org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.m_parallel private
Definition at line 196 of file CProxyAction.java.
Referenced by org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.CActionWrapper(), and org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper.execute().