LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.instantiable.IBaseInstantiable Class Reference
org.lightjason.agentspeak.language.instantiable.IBaseInstantiable Class Reference abstract
base structure of instantiable elements
Public Member Functions
final boolean equals (final Object p_object)
IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
defines a plan-body operation
final int hashCode ()
final IContext instantiate (final IAgent<?> p_agent, final Stream< IVariable<?>> p_variable)
creates an individual execution context
double score (final IAgent<?> p_agent)
returns the scoring value of the execution structure
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Protected Member Functions
IBaseInstantiable (final List< IExecution > p_action, final Set< IAnnotation<?>> p_annotation, final int p_hash)
ctor
Protected Attributes
final List< IExecution > m_action
action list
final Map< IAnnotation.EType,
IAnnotation<?> > m_annotation
map with annotation (enum value for getting annotation object)
Private Member Functions
List< IFuzzyValue< Boolean > > executeparallel (final IContext p_context)
execute plan parallel
List< IFuzzyValue< Boolean > > executesequential (final IContext p_context)
execute plan sequential
Private Attributes
final int m_hash
hash code
Detailed Description
Definition at line 49 of file IBaseInstantiable.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.IBaseInstantiable (final List< IExecution > p_action, final Set< IAnnotation<?>> p_annotation, final int p_hash) protected
Parameters
p_action executed actions
p_annotation annotation map
p_hash hash code
Definition at line 72 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action, org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_annotation, and org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_hash.
Member Function Documentation
final boolean org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.equals (final Object p_object)
Definition at line 86 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.hashCode().
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
Parameters
p_context current execution context
p_parallel parallel execution
p_argument parameter of the action
p_return return values
p_annotation annotation
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 119 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.execution.IContext.agent(), and org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.executeparallel().
List<IFuzzyValue<Boolean> > org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.executeparallel (final IContext p_context) private
Parameters
p_context execution context
Returns
list with execution results
Note
each element is executed
Definition at line 168 of file IBaseInstantiable.java.
Referenced by org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.execute().
List<IFuzzyValue<Boolean> > org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.executesequential (final IContext p_context) private
Parameters
p_context execution context
Returns
list with execution results
Note
stream is stopped iif an execution is failed
Definition at line 143 of file IBaseInstantiable.java.
final int org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.hashCode ()
Definition at line 80 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_hash.
Referenced by org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.equals().
final IContext org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.instantiate (final IAgent<?> p_agent, final Stream< IVariable<?>> p_variable)
Parameters
p_agent agent
p_variable variable stream
Returns
individual context
Implements org.lightjason.agentspeak.language.instantiable.IInstantiable.
Definition at line 107 of file IBaseInstantiable.java.
double org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.score (final IAgent<?> p_agent)
Parameters
p_agent agent for which calculates the score value
Returns
score value
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 92 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action, and org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_annotation.
Stream<IVariable<?> > org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 113 of file IBaseInstantiable.java.
References org.lightjason.agentspeak.language.execution.IExecution.variables().
Member Data Documentation
final List<IExecution> org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_action protected
Definition at line 54 of file IBaseInstantiable.java.
Referenced by org.lightjason.agentspeak.language.instantiable.plan.CPlan.getBodyActions(), org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.IBaseInstantiable(), org.lightjason.agentspeak.language.instantiable.rule.CRule.replaceplaceholder(), org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.score(), org.lightjason.agentspeak.language.instantiable.rule.CRule.toString(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.toString().
final Map<IAnnotation.EType, IAnnotation<?> > org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_annotation protected
Definition at line 59 of file IBaseInstantiable.java.
Referenced by org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.IBaseInstantiable(), org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.score(), org.lightjason.agentspeak.language.instantiable.plan.CPlan.score(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.toString().
final int org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.m_hash private
Definition at line 63 of file IBaseInstantiable.java.
Referenced by org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.hashCode(), and org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.IBaseInstantiable().