LightJason - AgentSpeak(L++): org.lightjason.agentspeak.agent.unify.CUnifier Class Reference
org.lightjason.agentspeak.agent.unify.CUnifier Class Reference
unification algorithm
Public Member Functions
CUnifier ()
ctor
CUnifier (final IAlgorithm p_hashbased, final IAlgorithm p_recursive)
ctor
final boolean equals (final Object p_object)
final int hashCode ()
final Set< IVariable<?> > literal (final ILiteral p_literal, final ILiteral p_value)
unifies a literal
final IFuzzyValue< Boolean > parallel (final IContext p_context, final ILiteral p_literal, final long p_variablenumber, final IExpression p_expression)
unifies a literal in parallel - checks all possible literals in parallel with the given expression, first expression which finish successful is the result
final IFuzzyValue< Boolean > sequential (final IContext p_context, final ILiteral p_literal, final long p_variablenumber, final IExpression p_expression)
unifies a literal in sequential - checks all possible literals in sequential with the given expression, first expression which finish successful is the result
final String toString ()
final IFuzzyValue< Boolean > unify (final IContext p_context, final ILiteral p_literal, final long p_variablenumber)
unifies a literal - first found literal matches within the beliefbase
Private Member Functions
List< Set< IVariable<?> > > unify (final IAgent<?> p_agent, final ILiteral p_literal, final long p_variablenumber)
search all relevant literals within the agent beliefbase and unifies the variables
Private Attributes
final IAlgorithm m_hashbased
hash-based unify algorithm
final IAlgorithm m_recursive
recursive unify algorithm
Detailed Description
Definition at line 49 of file CUnifier.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.agent.unify.CUnifier.CUnifier ()
Definition at line 63 of file CUnifier.java.
org.lightjason.agentspeak.agent.unify.CUnifier.CUnifier (final IAlgorithm p_hashbased, final IAlgorithm p_recursive)
Parameters
p_hashbased hash-based unification algorithm
p_recursive recursive-based unification algorithm
Definition at line 74 of file CUnifier.java.
References org.lightjason.agentspeak.agent.unify.CUnifier.m_hashbased, and org.lightjason.agentspeak.agent.unify.CUnifier.m_recursive.
Member Function Documentation
final boolean org.lightjason.agentspeak.agent.unify.CUnifier.equals (final Object p_object)
Definition at line 221 of file CUnifier.java.
References org.lightjason.agentspeak.agent.unify.CUnifier.hashCode().
final int org.lightjason.agentspeak.agent.unify.CUnifier.hashCode ()
Definition at line 213 of file CUnifier.java.
References org.lightjason.agentspeak.agent.unify.CUnifier.m_recursive.
Referenced by org.lightjason.agentspeak.agent.unify.CUnifier.equals().
final Set<IVariable<?> > org.lightjason.agentspeak.agent.unify.CUnifier.literal (final ILiteral p_literal, final ILiteral p_value)
Parameters
p_literal literal with variables (creates a deep-copy)
p_value source literal with values
Returns
set with allocated variables
Note
check input literal and result of correct unification
Implements org.lightjason.agentspeak.language.execution.action.unify.IUnifier.
Definition at line 170 of file CUnifier.java.
References org.lightjason.agentspeak.language.ILiteral.annotationhash(), org.lightjason.agentspeak.language.ILiteral.annotations(), org.lightjason.agentspeak.agent.unify.CUnifier.m_hashbased, org.lightjason.agentspeak.language.ILiteral.orderedvalues(), org.lightjason.agentspeak.language.CCommon.recursiveliteral(), org.lightjason.agentspeak.language.CCommon.recursiveterm(), org.lightjason.agentspeak.agent.unify.IAlgorithm.unify(), and org.lightjason.agentspeak.language.ILiteral.valuehash().
final IFuzzyValue<Boolean> org.lightjason.agentspeak.agent.unify.CUnifier.parallel (final IContext p_context, final ILiteral p_literal, final long p_variablenumber, final IExpression p_constraint)
Parameters
p_context running context
p_literal literal with variables (creates a deep-copy)
p_variablenumber number of unified variables
p_constraint expression
Returns
boolean if a unify can be done
Implements org.lightjason.agentspeak.language.execution.action.unify.IUnifier.
Definition at line 96 of file CUnifier.java.
final IFuzzyValue<Boolean> org.lightjason.agentspeak.agent.unify.CUnifier.sequential (final IContext p_context, final ILiteral p_literal, final long p_variablenumber, final IExpression p_constraint)
Parameters
p_context running context
p_literal literal with variables (creates a deep-copy)
p_variablenumber number of unified variables
p_constraint expression
Returns
boolean if a unify can be done
Implements org.lightjason.agentspeak.language.execution.action.unify.IUnifier.
Definition at line 133 of file CUnifier.java.
final String org.lightjason.agentspeak.agent.unify.CUnifier.toString ()
Definition at line 227 of file CUnifier.java.
References org.lightjason.agentspeak.agent.unify.CUnifier.m_hashbased, and org.lightjason.agentspeak.agent.unify.CUnifier.m_recursive.
final IFuzzyValue<Boolean> org.lightjason.agentspeak.agent.unify.CUnifier.unify (final IContext p_context, final ILiteral p_literal, final long p_variablenumber)
Parameters
p_context running context
p_literal literal with variables (creates a deep-copy)
p_variablenumber number of unified variables
Implements org.lightjason.agentspeak.language.execution.action.unify.IUnifier.
Definition at line 84 of file CUnifier.java.
List<Set<IVariable<?> > > org.lightjason.agentspeak.agent.unify.CUnifier.unify (final IAgent<?> p_agent, final ILiteral p_literal, final long p_variablenumber) private
Parameters
p_agent agent
p_literal literal search
p_variablenumber number of unified variables
Returns
list of literal sets
Definition at line 241 of file CUnifier.java.
Member Data Documentation
final IAlgorithm org.lightjason.agentspeak.agent.unify.CUnifier.m_hashbased private
Definition at line 54 of file CUnifier.java.
Referenced by org.lightjason.agentspeak.agent.unify.CUnifier.CUnifier(), org.lightjason.agentspeak.agent.unify.CUnifier.literal(), and org.lightjason.agentspeak.agent.unify.CUnifier.toString().
final IAlgorithm org.lightjason.agentspeak.agent.unify.CUnifier.m_recursive private
Definition at line 58 of file CUnifier.java.
Referenced by org.lightjason.agentspeak.agent.unify.CUnifier.CUnifier(), org.lightjason.agentspeak.agent.unify.CUnifier.hashCode(), and org.lightjason.agentspeak.agent.unify.CUnifier.toString().